### ISSUE TITLE
Support AWS Secret Manager

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1006]
https://aws.amazon.com/secrets-manager/

Probably similar to our support for AWS parameter store.

**Comment by tburch** [comment]
@sdelamo if you have an outline of how you envision this working, I'd be happy to help with a PR.

**Comment by sdelamo** [comment]
> @sdelamo if you have an outline of how you envision this working, I'd be happy to help with a PR.

@tburch I am working on this PR: https://github.com/micronaut-projects/micronaut-aws/pull/1056

**Comment by sdelamo** [comment]
@tburch I am writing a guide as well: https://github.com/micronaut-projects/micronaut-guides/pull/239
