### ISSUE TITLE
HttpResponse not working properly inside lambda environment using graalvm

### ISSUE THREAD

**Issue by pulsarix** [micronaut-projects/micronaut-aws#105]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Follow steps from https://bitbucket.org/traycho/micronaut-examples/src/master/
1. Build application
2. Run it in sam local environment
3. Execute curl -G http://localhost:3000/ping

### Expected Behaviour
Application should behave same running standard jar or graalvm compiled binary.
Executing ```curl -G http://localhost:3000/ping``` should result into ```{ "message": "ping"}```

### Actual Behaviour
Executing ```curl -G http://localhost:3000/ping```  results into {}
Using HttpResponse returned by controller methods results into {} empty body.

### Environment Information

- **Operating System**:  MacOs Sierra
- **Micronaut Version:** 1.2.4
- **JDK Version:** 1.8.0_222

### Example Application
Checkout code from
https://bitbucket.org/traycho/micronaut-examples/src/master/

**Comment by traycho** [comment]
I tried to upgrade to 1.3.6 but still issue is present. On top the response is always 200

aws-sam-cli version is 0.47.0 
https://bitbucket.org/traycho/micronaut-examples/src/master/

@alvarosanchez  I am not 100% if this is micronaut issue or aws sam cli doing something wrong.

**Comment by alvarosanchez** [comment]
Micronaut 1.3.6's BOM contains Micronaut AWS 1.3.9.

This issue was shipped in Micronaut AWS 1.4.0

**Comment by traycho** [comment]
@alvarosanchez Thanks for the fast feedback confirming io.micronaut.aws:micronaut-function-aws-api-proxy:1.4.0 is solving the issue.
