### ISSUE TITLE
Include Null Value Keys In Response from Micronaut AWS serverless Function

### ISSUE THREAD

**Issue by mayurtanna** [micronaut-projects/micronaut-aws#1077]
I have a Micronaut serverless function deployed on AWS lambda.

By default, it is excluding the null values from response but I need them. I tried following ways to solve the issue but no luck.

### Solution Tried

- Added below in application.yml
  jackson: serializationInclusion: ALWAYS

- Added @JsonInclude(JsonInclude.Include.ALWAYS) on POJOs which are getting sent in response.

- Tried to override ObjectMapper using the following code:
  
  ```
  @Singleton static class ObjectMapperBeanEventListener implements BeanCreatedEventListener {
  @Override
   public ObjectMapper onCreated(BeanCreatedEvent<ObjectMapper> event) {
     logger.info("oncreated objectmapper");
     ObjectMapper mapper = event.getBean();
     mapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);
     mapper.configure(SerializationFeature.WRITE_NULL_MAP_VALUES, true);
     mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
     logger.info("oncreated objectmapper exited");
     return mapper;
   }
 }


### Steps to Reproduce

1. Hit the function that return response.
2. Check if the response returns keys with null values.


### Expected Behaviour

Response should return keys with null values.

### Actual Behaviour

Response doesn't include null value keys.

### Environment Information


- **Micronaut Version:** 2.2.3
- **JDK Version:** JDK 11

### Example Application

https://github.com/mayurtanna/micronaut-aws-function

**Comment by mayurtanna** [comment]
@sdelamo Can you please help here ?

**Comment by sdelamo** [comment]
@mayurtanna I am going to check this now.

**Comment by sdelamo** [comment]
If you have a function which returns a POJO such as: 

```java
package com.example;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;

import javax.validation.constraints.NotBlank;

@Introspected
public class Book {

    @NonNull
    @NotBlank
    private String name;

    @Nullable
    private Integer pages;

    public Book(@NonNull String name) {
        this.name = name;
    }

    public Book(@NonNull String name, @Nullable Integer pages) {
        this.name = name;
        this.pages = pages;
    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    @Nullable
    public Integer getPages() {
        return pages;
    }

    public void setPages(@Nullable Integer pages) {
        this.pages = pages;
    }
}
```

and you want to receive a JSON which includes nulls: 

```json
{ "body": "{"name":"Building Microservices","pages":null}",
``` 

You have several options:

**Annotation in the field**

Using `@JsonInclude(JsonInclude.Include.ALWAYS)` annotation in the field:

```java
....
@Introspected
public class Book {
...
..
.
    @JsonInclude(JsonInclude.Include.ALWAYS)
    @Nullable
    private Integer pages;
...
```

**Via Configuration**

You could use configuration such as: 

_src/main/resources/application.yaml_
```yaml
jackson:
  serialization-inclusion: always
```

**Or Listen for the creation of ObjectMapper and configure it.** 

```java
package com.example;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.context.event.BeanCreatedEvent;
import io.micronaut.context.event.BeanCreatedEventListener;
import io.micronaut.inject.BeanDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Named;
import javax.inject.Singleton;
import java.util.Optional;

//@Singleton
public class ObjectMapperBeanCreatedEventListener implements BeanCreatedEventListener<ObjectMapper> {
    @Override
    public ObjectMapper onCreated(BeanCreatedEvent<ObjectMapper> event) {
        ObjectMapper bean = event.getBean();
        getNamedValue(event.getBeanDefinition()).ifPresent(v ->
                bean.setSerializationInclusion(JsonInclude.Include.ALWAYS));
        return bean;
    }

    private Optional<String> getNamedValue(BeanDefinition<?> beanDefinition) {
        // Micronaut 2
        return beanDefinition
                .findAnnotation(Named.class)
                .map(n -> (String) n.getValues().get("value"));
        // Micronaut 3
        //AnnotationValue<Annotation> annotationAnnotationValue = beanDefinition.getAnnotation(AnnotationUtil.NAMED);
        //if (annotationAnnotationValue == null) {
        // return Optional.empty();
        //}
        //return annotationAnnotationValue.getValue(String.class);
    }
}
```

## Application with `aws-lambda` feature

All of the above work, for a [Application with  `aws-lambda` feature](https://micronaut.io/launch?javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&name=demo&package=com.example&type=DEFAULT&features=aws-lambda)

<img width="688" alt="Screenshot 2021-07-30 at 07 38 21" src="https://user-images.githubusercontent.com/864788/127606012-dba06be3-a123-4c5f-ae0b-0570194513e8.png">

In such a Lambda App, you use controllers.:

```java
package com.example;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller
public class BookController {

    @Get
    public Book index() {
        return new Book("Building Microservices");
    }
}
```

In this scenario, as a Lambda Handler, you use `io.micronaut.function.aws.proxy.MicronautLambdaHandler`.

## Function Application For Serverless with `aws-lambda` feature

For a [`Function Application for Serverless` with  `aws-lambda` feature](https://micronaut.io/launch?javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&name=demo&package=com.example&type=FUNCTION&features=aws-lambda&version=2.5.11)

<img width="455" alt="Screenshot 2021-07-30 at 07 46 43" src="https://user-images.githubusercontent.com/864788/127606716-7bff3294-b4d4-41cd-9c64-5f58555b0135.png">

If you use such a Handler:

```java
package com.example;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.function.aws.MicronautRequestHandler;

@Introspected
public class BookRequestHandler extends MicronautRequestHandler<Void, Book> {

    @Override
    public Book execute(Void input) {
        return new Book("Building Microservices");
    }
}
```

**None of the above will work.** 

In order to use the `ObjectMapper` configured by Micronaut to render the POJO, you will need to use `MicronautRequestStreamHandler`  which implements AWS  `com.amazonaws.services.lambda.runtime.RequestStreamHandler`

You will set your Handler in the AWS Console to `com.example.BookStreamRequestHandler` and have code such as: 

```java
package com.example;

import io.micronaut.context.env.Environment;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.function.aws.MicronautRequestStreamHandler;

@Introspected
public class BookStreamRequestHandler extends MicronautRequestStreamHandler {
    @Override
    protected String resolveFunctionName(Environment environment) {
        return "book";
    }
}
```

```java
package com.example;

import io.micronaut.function.FunctionBean;

import java.util.function.Function;

@FunctionBean("book")
public class BookFunction implements Function<Void, Book> {
    @Override
    public Book apply(Void unused) {
        return new Book("Building Microservices");
    }
}

```

**Comment by mayurtanna** [comment]
@sdelamo  Thanks for working on this. 

Your solution seems to be working except that I am getting the following error when using MicronautStreamRequestHandler in my project. I am using mongo-sync for mongodb connectivity.

Any pointer on this ? 

Connection pool shut down: java.lang.IllegalStateException
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:8

**Comment by sdelamo** [comment]
@mayurtanna Please, create a different issue with a reproducible example. I don't know how to help you with the above info.

**Comment by mayurtanna** [comment]
@sdelamo Okay. I will. Thank you. 

Can you confirm following things please ?

1. Do we documentation for MicronautStreamHandler and @functionalbean? I didn't find it anywhere.  If you have any reference, please share.
2. Can we use MicronautStreamHandler with mongodb-sync or we need to use mongo-reactive ?

**Comment by sdelamo** [comment]
> Do we documentation for MicronautStreamHandler and @functionalbean? I didn't find it anywhere. If you have any reference, please share.

see: 

https://micronaut-projects.github.io/micronaut-aws/latest/guide/#lambdaStreamHandler

> Can we use MicronautStreamHandler with mongodb-sync or we need to use mongo-reactive ?

i don't know your Lambda code relates to MongoBD. I don't know how to answer you question.

**Comment by mayurtanna** [comment]
@sdelamo  Thanks for the link of the document. And I apologize for the confusing language. Actually, we have a lambda function that inserts data in mongo db. It is working fine when I use MicronautRequestHandler but gives connection pool error when using MicronautRequestStreamHandler which is really weird. It might be due to some conflicts with SSMClient or something else that is closing the connection pool but not getting the exact issue.

**Comment by sdelamo** [comment]
> @sdelamo Thanks for the link of the document. And I apologize for the confusing language. Actually, we have a lambda function that inserts data in mongo db. It is working fine when I use MicronautRequestHandler but gives connection pool error when using MicronautRequestStreamHandler which is really weird. It might be due to some conflicts with SSMClient or something else that is closing the connection pool but not getting the exact issue.

That it is strange that it works with `MicronautRequestHandler`but it does not with `MicronautRequestStreamHandler`

**Comment by mayurtanna** [comment]
@sdelamo  Yes and I think the problem is with the StreamFunctionExecutor class's execute method which is getting called internally when we use MicronautRequestStreamHandler. In the execute method it is closing the applicationContext in finally clause which seem to be destroying MongoClient and hence we are getting this exception regarding connection on next request. Is this understanding correct ? I will be create a new issue regarding the same but do you have any thoughts here ?

**Comment by sdelamo** [comment]
do you mind if we move this to a [discussions](https://github.com/micronaut-projects/micronaut-aws/discussions) to keep the history of this issue as clean as possible?
