### ISSUE TITLE
Micranaut is unable to route a URI path if it has an encoded '+' character as '%2B' in the URI path when running as AWS API gateway lambda or ECS service

### ISSUE THREAD

**Issue by afatykhov** [micronaut-projects/micronaut-aws#110]
Micranaut is unable to route a URI path if it has an encoded '+' character as '%2B' when running as AWS API gateway lambda or ECS service, I suspect it is a common issue of the DefaultRoute class in the code.

In the case with the AWS API Gateway lambda , it will respond  with the 404 as well:

```java
@Slf4j
public class ServiceLambdaHandler implements RequestStreamHandler {
    private static MicronautLambdaContainerHandler handler;
    static {
        try {
            handler = MicronautLambdaContainerHandler.getAwsProxyHandler();
        } catch (ContainerInitializationException e) {
            // if we fail here. We re-throw the exception to force another cold start
            throw new RuntimeException("Could not initialize Service Idm", e);
        }
    }
    @Override
    public void handleRequest(InputStream input, OutputStream output, Context context) throws IOException {
        handler.proxyStream(input, output, context);
    }
}
```

### Steps to Reproduce

Create a REST service:

```java
    @Post(value = "/{someId}", produces = MediaType.APPLICATION_JSON,consumes = MediaType.APPLICATION_JSON)
    ServiceAuthenticationResponse authenticateService(@NotNull @PathVariable("someId") String someId, @Body @Valid RequestPayload reqPayload); 
```

when request URL is https://address/a.fatykhov@company.com .  , Micronaut is routing to a right controller method.

when request URL is https://address/a.fatykhov%2B1@company.com   , Micronaut is unable to route request, the response from the service in this case is:

404

```javascript
{
  "message" : "Page Not Found",
  "_links" : {
    "self" : {
      "href" : "a.fatykhov+1@company.com",
      "templated" : false
    }
  }
}
```

### Expected Behaviour

Micronaut must correctly route encoded '+' in the path parameters in AWS environment when it is running behind API gatway as a REST lambda or Fargate ECS service.  

### Actual Behaviour

It cannot route the URI to a registered controllers.it fails with 404.
I suspect route matcher is no handling '+' correctly in the URI . if regular expression is used to match routes, it should escape '+' first before matching.

### Environment Information

- Operation System: Linux
- Micronaut Version: 1.2.0
- JDK Version: 1.8.XXX

**Comment by afatykhov** [comment]
if I hack the class DefaultRouter.java
as:
private <T, R> Stream<UriRouteMatch<T, R>> find(String httpMethodName, CharSequence uri) {
List routes = routesByMethod.getOrDefault(httpMethodName, Collections.emptyList());
// also, need to re-encode only the path section of the URI
final String path = uri.toString().replaceAll("\+", "%2B");
return routes.stream()
.map((route -> route.match(path)))
.filter(Optional::isPresent)
.map(Optional::get);
}

it will work fine (omitting '+' ->' ' case ) and route will be matched with the '+' in the path section,
but I think we need a proper fix that can be controlled by Micronaut configuration.

**Comment by afatykhov** [comment]
Micronaut can be used with the API Gateway in two cases:
  1. AWS Lambda proxy
  2. ESC EC2 service
we need a fix for both (basically the same code is responsible for the route match in both cases).

**Comment by afatykhov** [comment]
Hi James,
  Do we have a time line for this issue to be fixed ?
Al

**Comment by graemerocher** [comment]
@afatykhov would you like to send a PR with a fix?

**Comment by afatykhov** [comment]
Hi Graeme,
  I can make a PR, although the issue is in the micronaut-core project because it is where DefaulRouter class resign, I have a fix for it.
I will post a PR.
Al

**Comment by graemerocher** [comment]
I thought you mentioned that `SpringBoot lambda/http deals with this just fine by re-encoding the URI` in which case it would be in the AWS project.

**Comment by afatykhov** [comment]
There are actually 2 issues, bot of the related to AWS and encoding of the '+'. in the URI.
   1. Micronaut service running as a lambda behind AWS API gateway.  
       issue can be solved in the io.micronaut.function.aws.proxy.MicronautRequestReader as:
    protected String fixPath(String path) {
        path = path.replaceAll("\\+", "%2B");
        return path;
    }

    @Override
    public MicronautAwsProxyRequest<?> readRequest(
            AwsProxyRequest request,
            SecurityContext securityContext,
            Context lambdaContext,
            ContainerConfig config) throws InvalidRequestEventException {
        try {
            final String path = config.isStripBasePath() ? stripBasePath(request.getPath(), config) : getPathNoBase(request);
            final MicronautAwsProxyRequest<?> containerRequest = new MicronautAwsProxyRequest(
                    **fixPath(path),**
                    request,
                    securityContext,
                    lambdaContext,
                    config
            );
Check 'fixPath' usage in the request.
And in the class MicronautLambdaContainerHandler.java
as:     
   @Override
    protected void handleRequest(
            MicronautAwsProxyRequest<?> containerRequest,
            MicronautAwsProxyResponse<?> containerResponse,
            Context lambdaContext) {
        Timer.start(TIMER_REQUEST);
        String path = containerRequest.getPath();
        try {
            // process filters & invoke servlet
            ServerRequestContext.with(containerRequest, () -> {
                Optional<UriRouteMatch> routeMatch = containerRequest.getAttribute(
                        HttpAttributes.ROUTE_MATCH,
                        UriRouteMatch.class
                );
                final Stream<UriRouteMatch<Object, Object>> matches = lambdaContainerEnvironment
                        .getRouter()
                        .findAny(**fixPath**(containerRequest.getPath()));
                Optional<UriRouteMatch<Object, Object>> first = matches.findFirst();
                if (routeMatch.isPresent() || first.isPresent()) {


2. The more generic issue is when Micronaut service is running as a ECS Fargate service behind AWS API gateway, It is the same problem with encoding of the '+', however service is a normal  web service and there is not AWS proxy evolved. In this case AWS API decodes encoded '+' and sends it to the Micronaut service as a plain '+' in the URL, unfortunately micronaut is unable to match the route in this case. To fix this we need to fix DefaultRouter class and add some sort of configuration to reencode the route before matching if it is behind API gateway. this fix will also address Micronaut Lambda and '+' issue as well. However this will require fixing micronaut-core project:
  DefaultRouter.java:

    private <T, R> Stream<UriRouteMatch<T, R>> find(String httpMethodName, CharSequence uri) {
        List<UriRoute> routes = routesByMethod.getOrDefault(httpMethodName, Collections.emptyList());       
        final String path = isAPIGateway()? uri.toString().replaceAll("\\+", "%2B"): uri.toString();               
        return routes.stream()
                .map((route -> route.match(path)))
                .filter(Optional::isPresent)
                .map(Optional::get);
    }

   private boolean isAPIGateway(){}

this more generic fix.

**Comment by afatykhov** [comment]
or fix can be done inside the route.match(path) call.

**Comment by afatykhov** [comment]
Meanwhile this is a real showstopper to use Micronaut service in AWS.

**Comment by afatykhov** [comment]
in the AWS API Gateway case the request path  %2B will become + and Micronaut will assume it is ‘ ’ space and will not match the route. Double encoding helps but it is not a solution.

**Comment by afatykhov** [comment]
Example of the ECS fargate integration, if it would help:
  TestServiceAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${EnvName}
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref AWS::StackName
        schemes:
          - "https"
        paths:            
          /{proxy+}:
            x-amazon-apigateway-any-method:
              parameters:
                - name: "proxy"
                  in: "path"
                  required: true
                  schema:
                    type: "string"
              responses: {}
              x-amazon-apigateway-integration:
                uri: 
                  !Join
                    - ''
                    - - 'http://'
                      - !GetAtt ServiceNetworkLoadBalancer.DNSName
                      - ':30080/{proxy}'
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "http_proxy"
                connectionType: 'VPC_LINK'
                connectionId: !Ref LoadBalancerVpcLink
                requestParameters:
                  integration.request.path.proxy: "method.request.path.proxy"

AWS API gateway decodes incoming URI (including %2B -> +) before passing it to Micronaut back end, and micronaut service is unable to find a mapping API.

**Comment by alvarosanchez** [comment]
@afatykhov we have been discussing internally about this issue. The fact that AWS API Gateway encodes the `+` character is definitely not an issue in Micronaut.

The problem when you send a request to `https://address/a.fatykhov%2B1@company.com` through an AWS API Gateway is that what Micronaut really gets is `https://address/a.fatykhov+1@company.com`, and that doesn't match the template `/{someId}`, because `+` is a reserved character. 

However, if you change the template to `{+someId}`, it will match correctly.

I have created this test case that is passing:

```groovy
@Unroll
void "Test URI template #template matches uri with encoded characters: #uri"() {
    given:
    UriMatchTemplate matchTemplate = new UriMatchTemplate(template)
    Optional<UriMatchInfo> info = matchTemplate.match(uri)

    expect:
    info.isPresent() == matches
    info.orElse(null)?.variableValues == variables

    where:
    template        | uri                           | matches   | variables
    "/{someId}"     | '/username@company.com'       | true      | [someId: 'username@company.com']
    "/{someId}"     | '/username%2B1@company.com'   | true      | [someId: 'username%2B1@company.com']
    "/{someId}"     | '/username+1@company.com'     | false     | null

    "/{+someId}"    | '/username@company.com'       | true      | [someId: 'username@company.com']
    "/{+someId}"    | '/username%2B1@company.com'   | true      | [someId: 'username%2B1@company.com']
    "/{+someId}"    | '/username+1@company.com'     | true      | [someId: 'username+1@company.com']
}
```

As you can see, the template `/{+someId}` matches in all cases, and is what you should use in your case.
