### ISSUE TITLE
Add support for Secret Manager for RDS instance 

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-aws#1106]
When creating Secret for RDS with autorotate feature the secret is created in format:
![Screenshot 2021-06-24 at 19 04 20](https://user-images.githubusercontent.com/1838702/123306845-143bcd80-d522-11eb-88a1-846ac6c214c5.png)

From Micronaut perspective there's no way how to adjust the secret key name so it would respect the micronaut context path like `datasources.default.username` so it would be automatically configured. The lambda function that handles the rotation expects exact format [2].

Because of this it would be great to have a way how to either:
A) add the prefix for the properties before they are injected into context:
```
micronaut:
  config-client:
    enabled: true
    aws-secret-manager:
       - <secret-name>:
         prefix: datasources.default
```

B) Provide an datasource bean initialization handler very similar to [3] that based on secret name would do all the configuration for the user.
```
datasources:
  default:
     aws-secret-name: <secret-name>
```

C) ??

[1]  https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_cloudformation.html
[2] https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py
[3] https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java

**Comment by sbodvanski** [comment]
The solution has been provided in:
https://github.com/micronaut-projects/micronaut-aws/pull/1481
