### ISSUE TITLE
String POST parameters get populated with full body

### ISSUE THREAD

**Issue by rnielsen** [micronaut-projects/micronaut-aws#1164]
### Expected Behavior

A POST method like

```
@Post("/stringParams")
public Map stringParams(String a, String b) {
    return Map.of("a", a, "b", b);
}
```
when invoked with a body of `{"a":"A","b":"B","c":"C"}` should populate parameters a and b with A and B respectively.

### Actual Behaviour

a and b are both being populated with the full JSON body. eg  `{"a":"A","b":"B","c":"C"}` 

Changing build.gradle to runtime('netty') instead of runtime('lambda') produces the expected result.

### Steps To Reproduce

Run `gradle test` on included project or `gradle run` and use curl
```
curl http://localhost:8080/stringParams -H 'Content-Type:application/json' --data '{"a":"A", "b":"B", "c":"C"}'
```

### Environment Information

- MacOS
- Java 11

### Example Application

https://github.com/rnielsen/micronaut-param

### Version

3.0.0

**Comment by sdelamo** [comment]
I always create POJOs to encapsulate the body payloads. 

@rnielsen this is a workaround  which will work for you:

```groovy
Map stringParams(@Body BodyPogo bodyPogo) 
```

```groovy
package com.example

import io.micronaut.core.annotation.Introspected

@Introspected
class BodyPogo {
    String a
    String b
}

```
