### ISSUE TITLE
GraalVM native-image support for ARM64 architectures

### ISSUE THREAD

**Issue by msailes** [micronaut-projects/micronaut-aws#1195]
### Feature description

AWS Lambda now supports ARM64 architecture. It would be great if I could create a ARM64 native binary to target this.

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

GraalVM supports ARM64
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0

**Comment by cristim** [comment]
Got it, thanks and sorry for the misunderstanding
