### ISSUE TITLE
io.micronaut.function.aws.MicronautRequestStreamHandler  has no public zero-argument constructor

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#128]
# Steps to reproduce

1. $ mn create-function test --inplace      
1. $ ./gradlew shadowJar
3. Create a lambda function in AWS console with Java runtime. 
4. Upload the zip file as handler set `io.micronaut.function.aws.MicronautRequestStreamHandler` and try to invoke the lambda with a test event

<img width="1012" alt="Screenshot 2019-11-18 at 11 04 59" src="https://user-images.githubusercontent.com/864788/69043613-acdba480-09f3-11ea-842a-de4548d5f758.png">

# Versions

Micronaut 1.2.6

**Comment by kairsas** [comment]
I understand that this fix is included in micronaut-function-aws 1.3.6.
But I see that 1.2.7 micronaut-bom artifact still uses dependency of micronaut-function-aws 1.3.3.
Could this be updated also?

**Comment by graemerocher** [comment]
Yes makes sense. Feel free to send a PR https://github.com/micronaut-projects/micronaut-core/blob/1.2.x/gradle.properties#L40
