### ISSUE TITLE
Document @MicronautLambdaTest

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1393]
### Issue description

see: https://github.com/micronaut-projects/micronaut-aws/tree/master/function-aws-test

https://micronaut-projects.github.io/micronaut-aws/snapshot/api/index.html

**Comment by hollingsworthd** [comment]
Is is already there? https://micronaut-projects.github.io/micronaut-aws/latest/guide/#lambdaTesting
