### ISSUE TITLE
Duplicate decoding of query parameters arriving from Api Gateway proxy

### ISSUE THREAD

**Issue by kairsas** [micronaut-projects/micronaut-aws#1407]
### Expected Behavior

Query parameter values with a special symbols should have correct values.

### Actual Behaviour

This happens when running micronaut controller in AWS env on `MicronautLambdaRuntime` with Api Gateway proxy integration.

If a query parameter is passed which contains special symbols like `+` and is passed url encoded, e.g.:
```curl  https://....execute-api.eu-west-2.amazonaws.com/mn-query-param-test/mypath?param=aa%2Bbb```

Then it is double decoded and controller receives a value of `aa bb`, but it should be `aa+bb`.

The thing is that Api Gateway decodes the param itself and passes `aa+bb` in the payload (`AwsProxyRequest`) to micronaut, which again does redudant decoding in `io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.AwsParameters#get(java.lang.CharSequence)` and this results in a wrong value (`aa bb`).

### Steps To Reproduce

1. Use this controller code:
```
@Controller
open class TestController {
    @Get(value = "/mypath")
    fun index(@QueryValue(value = "param") param: String) = mapOf("param" to param)
}
```
2. Deploy it on Aws lambda as in (https://guides.micronaut.io/latest/mn-application-aws-lambda-java11-maven-kotlin.html)
3. Integrate it with Aws Api Gateway lambda proxy integration
4. Try calling ```curl  https://....execute-api....amazonaws.com/api-gw-stage/mypath?param=aa%2Bbb```
5. The response will be `{"param":"aa bb"}`, but should be `{"param":"aa+bb"}`

### Example Application

https://github.com/kairsas/mn-query-param-test/blob/master/src/main/kotlin/example/micronaut/HomeController.kt

### Version

2.\*, 3.\*

**Comment by mkairys-tru** [comment]
Would it be possible to port this to 2.* also?
