### ISSUE TITLE
AWS Secret Manager Integration: Allow configurable arbitrary secret prefixes

### ISSUE THREAD

**Issue by ChristianMattarVT** [micronaut-projects/micronaut-aws#1442]
### Feature description

I've been investigating the Micronaut AWS Secret Manager integration. Initial setup works like a charm.
However, in our setup we have several secrets which are shared in various ways among different applications, e.g.
Secret 1 is used by Application A and Application B
Secret 2 is used by Application B and Application C.

The AWS IAM permissions are set up so that each application only has access to secrets that it sees.
If we make the secrets available using a common prefix (e.g. based on commonApplicationName), then, once Micronaut encounters a secret to which it has no access, it will stop fetching due to the exception.

Some ideas for improvements:
- Allow an arbitrarily configurable list of secrets to scan, instead of just based on applicationName and commonApplicationName
- Recover gracefully when iterating through all the listed secrets, and one is encountered where access is denied. This would allow to scan all secrets that are stored and just load those that are accessible.

Thank you!

**Comment by breader124** [comment]
I managed to reproduce the issue described in the first post and will continue working on it
