### ISSUE TITLE
MicronautLambdaContainerHandler does not validates contentType ALL

### ISSUE THREAD

**Issue by pushpender673** [micronaut-projects/micronaut-aws#155]
Steps To reproduce
1. Create a Controller with POST request 
```  @Post(value = "/test", produces = APPLICATION_JSON, consumes = ALL) ``` 
2. Deploy application to AWS lambda
3. Try to hit the URL with content type application/json or anything

It does not matches to anything and throws 415 unsupported Media type.

ALL should match to anything.

**Comment by ShashankMishra** [comment]
Facing same issue.
Created a PR -https://github.com/micronaut-projects/micronaut-aws/pull/158
Keep an eye.

**Comment by graemerocher** [comment]
Thanks for the PR

**Comment by ShashankMishra** [comment]
@graemerocher 
There was a mismatch of type check hence condition was always returning true, Kindly merge the new PR raised for the fix -https://github.com/micronaut-projects/micronaut-aws/pull/172
