### ISSUE TITLE
Logging not Initializing: AWS Serverless Java Container forcing SLF4J API 2.0

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1560]
### Expected Behavior

Logging to work properly

### Actual Behaviour

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/<redacted>/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

### Steps To Reproduce

Create a new project using Micronaut AWS

### Environment Information

- Operating System: MacOS
- JVM Version: Corretto 11

### Version

3.8.0

**Comment by sdelamo** [comment]
How to reproduce the issue, create an app with a log statement and it will not appear?

**Comment by driverpt** [comment]
Yes, Serverless Function App in `/launch` for AWS Lambda

**Comment by driverpt** [comment]
Ok, managed to workaround it:
```
constraints {
        implementation("org.slf4j:slf4j-api:1.7.36") {
            version {
                strictly("1.7.36")
            }
        }
}
```

**Comment by sdelamo** [comment]
AWS Serverless Java Container  is only used for `Default application`
 not for `Serverless Function`

**Comment by driverpt** [comment]
Doesn't it come bundled with `micronaut-function-aws` ?

**Comment by sdelamo** [comment]
[no, micronaut-function-aws-api-proxy](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/build.gradle.kts#L10-L14)

**Comment by driverpt** [comment]
It's funny because i don't have that in my Classpath but SLF4J 2.x is there

**Comment by charlie-harvey** [comment]
I tried a whole bunch of ways to constrain a version and wound up with this:

```kotlin
configurations {
    all {
        resolutionStrategy.force("org.slf4j:slf4j-api:1.7.36")
    }
}
```

**Comment by sdelamo** [comment]
[I have created a PR which hopefully resolves the issue](https://github.com/micronaut-projects/micronaut-aws/pull/1570)

**Comment by sdelamo** [comment]
> It's funny because i don't have that in my Dependencies but SLF4J 2.x is there in the Classpath.

[The Gradle plugin adds that dependency for you automatically for the given runtime. ](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java#L65-L73)
