### ISSUE TITLE
Investigate HTTP Server TCK FailureSimpleRequestWithCorsNotEnabledTest

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1587]
### Issue description

[io.micronaut.http.server.tck.tests.cors.SimpleRequestWithCorsNotEnabledTest](https://github.com/micronaut-projects/micronaut-aws/commit/33ad5459c64c18d876d31443aa2c27c70a630535)

**Comment by timyates** [comment]
This passes on 3.13.x 👍 

The fix was in Micronaut 3.8.3 https://github.com/micronaut-projects/micronaut-core/releases/tag/v3.8.3
