### ISSUE TITLE
Building GraalVM example aws-api-gateway-graal from documentation fails

### ISSUE THREAD

**Issue by huksley** [micronaut-projects/micronaut-aws#161]
MacOS X version 10.14.6 
Local java (probably not used as I am building inside docker) installed by sdkman version: openjdk 11.0.5 2019-10-15
Micronaut (installed by sdkman): 1.2.8

## What happens?
During build exception reported: `Error: Error encountered while parsing io.micronaut.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(io.micronaut.caffeine.cache.Caffeine, io.micronaut.caffeine.cache.CacheLoader, boolean) 
Parsing context:
	parsing io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3026)`

`The command '/bin/sh -c /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/serverless-micronaut-*-all.jar' returned a non-zero code: 1`

build/function.zip have 0 size

## What you expect
Locally available build/function.zip
so deploy.sh can proceed deploying lambda as custom runtime to AWS

## Reproduce

```bash
mn create-app serverless-micronaut --features aws-api-gateway-graal
cd serverless-micronaut
./deploy.sh
```

Full log available here: https://gist.github.com/huksley/30d839d81bb8b44e14058291680647ce

I think this issue superceedes following ones (which can be closed):
- https://github.com/micronaut-projects/micronaut-aws/issues/49
- https://github.com/micronaut-projects/micronaut-aws/issues/106
- https://github.com/micronaut-projects/micronaut-aws/issues/24

**Comment by alvarosanchez** [comment]
See https://github.com/micronaut-projects/micronaut-aws/issues/106#issuecomment-546827880
