### ISSUE TITLE
investigate failures in server tck

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1634]
### Issue description

https://github.com/micronaut-projects/micronaut-aws/commit/dea9857302a5ad54815284546fed87a42661b82a

**Comment by timyates** [comment]
Low hanging fruit first https://github.com/micronaut-projects/micronaut-aws/issues/1634

**Comment by timyates** [comment]
Octet test fix https://github.com/micronaut-projects/micronaut-aws/pull/1636

**Comment by timyates** [comment]
RemoteAddressTest fix https://github.com/micronaut-projects/micronaut-aws/pull/1637

**Comment by timyates** [comment]
Mutable request failures: https://github.com/micronaut-projects/micronaut-aws/pull/1638
