### ISSUE TITLE
Support AWS Java SDK V2

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-aws#173]
According to AWS Lambda team, it is recommended to use version 2 of AWS SDK instead of V1 which is currently use in `aws-common`

see https://github.com/aws/aws-sdk-java-v2

It would be great if there is `aws-common-2` which will mirror the AWS SDK V2 API.

There is no `ClientConfiguration` in the V2 but it allows to choose HTTP client on your own. One of the options is also Netty HTTP Client which is already used by Micronaut. It would be great if the AWS SDK V2 calls can use the client already configured by Micronaut or use the same configuration mechanism as the current Micronaut's HTTP client.

see https://github.com/aws/aws-sdk-java-v2/tree/master/http-clients/netty-nio-client

**Comment by graemerocher** [comment]
This will require a major version bump

**Comment by musketyr** [comment]
I don't think so. the point is to support both (and enable just the ones which are present on the classpath). for example, there will be no good replacement of `DynamoDBMapper` soon so we will still need to use DynamoDB v1 alongside v2 services

**Comment by musketyr** [comment]
thanks!
