### ISSUE TITLE
`"aws.profile"` is not being picked for credentials during initialisation

### ISSUE THREAD

**Issue by yashLadha** [micronaut-projects/micronaut-aws#1748]
### Feature description

I am working on a simple CLI application and wanted to use the aws profile credentials provider for authentication. I was trying to set the aws profile using `application.yml` file.

Issue with this approach is that the credential provider in aws sdk use the system property and is not aware of micronaut environment specific capabilities.

Though there is a workaround to use following:

```java
        System.setProperty("aws.profile", awsProfile);
```

Fetch the value of `awsProfile` as following.

```java
    @Property(name = "aws.profile")
    private String awsProfile;
```

But this does not seems to be a nice solution to work with.

Ideally, it should read the profile env and select the profile credential provider.

Let me know if this something we want to have it in source. I am more than willing to contribute and send the PR.

**Comment by sdelamo** [comment]
@yashLadha do you have a sample application?
