### ISSUE TITLE
Cannot invoke \"com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent$RequestContext.getHttp()\" because the return value of \"com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent.getRequestContext()\" is null

### ISSUE THREAD

**Issue by Lacoz** [micronaut-projects/micronaut-aws#1806]
### Expected Behavior

Status 200 and hello world message wrapped as ApiGw2 response

### Actual Behaviour

{
  "errorMessage": "Cannot invoke \"com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent$RequestContext.getHttp()\" because the return value of \"com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent.getRequestContext()\" is null",
  "errorType": "java.lang.NullPointerException",
  "stackTrace": [
    "io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventServletRequest.<init>(APIGatewayV2HTTPEventServletRequest.java:58)",
    "io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventHandler.createExchange(APIGatewayV2HTTPEventHandler.java:55)",
    "io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventHandler.createExchange(APIGatewayV2HTTPEventHandler.java:35)",
    "io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:165)",
    "io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventFunction.handleRequest(APIGatewayV2HTTPEventFunction.java:56)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/java.lang.reflect.Method.invoke(Unknown Source)"
  ]
}

### Steps To Reproduce

I try Micronaut 4.0.0-Snapshot of AWS Lambda  as Micronaut application. Create project with MN Launch build Jar file and uploaded to AWS Lamdba Java 17 runtime.Then i set up handler to io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventFunction::handleRequest

And triggered the test from AWS Console 

![image](https://github.com/micronaut-projects/micronaut-aws/assets/1428538/1e62e04d-dcfc-4caa-ae6a-987d65e42cac)

### Environment Information

-  JDK 17.0.7 tem
- 

- IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9225.16, built on July 12, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-46-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.22.0)
    name.kropp.intellij.makefile (231.8109.91)
    net.ashald.envfile (3.4.1)
    aws.toolkit (1.71-231)

Kotlin: 231-1.8.21-IJ9225.16
Current Desktop: ubuntu:GNOME

### Example Application

https://github.com/Lacoz/kotlinws1

### Version

4.0.0-M8

**Comment by sdelamo** [comment]
if the test is using payload version 1 you should use `io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction` as your handler.
