### ISSUE TITLE
Regression in Lambda Native performance

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1812]
### Micronaut Framework 3

<img width="1650" alt="CleanShot 2023-07-18 at 15 58 29@2x" src="https://github.com/micronaut-projects/micronaut-aws/assets/864788/073024a0-870c-4242-82b0-755d116eb4c2">

### Micronaut Framework 4

<img width="1435" alt="CleanShot 2023-07-18 at 14 53 26@2x" src="https://github.com/micronaut-projects/micronaut-aws/assets/864788/e291b67b-54fd-4e5c-8a45-31dc02f6801d">

see cold startup times in the bottom right corner of the images have significantly increased in MN4.

**Comment by sdelamo** [comment]
Using Micronaut Jackson Databind helps 

<img width="1560" alt="CleanShot 2023-07-18 at 18 31 25@2x" src="https://github.com/micronaut-projects/micronaut-aws/assets/864788/00cf6e00-7e78-4de9-a430-1cda02f7fcf2">

**Comment by timyates** [comment]
@sdelamo did https://github.com/micronaut-projects/micronaut-aws/pull/1935 fix it?

**Comment by sdelamo** [comment]
No. unfortunately the regression is still present. 

I run [AWS Lambda Todo](https://github.com/micronaut-projects/micronaut-lambda-todo) load tests. 

For Micronaut Framework 4 (branch `master`). 

| Runtime                | Max Cold Startup ms | 
|:-----------------------|:--------------------|
| Java runtime           | 6849              |
| Native                 | 1131              |
| Java SnapStart         | 2960              |
| Java SnapStart Priming | 2267              |

For Micronaut Framework 4 (branch `micronaut-3`). 

| Runtime                | Max Cold Startup ms | 
|:-----------------------|:--------------------|
| Java runtime           | 8243              |
| Native                 | 922               |
| Java SnapStart         | 3625              |
| Java SnapStart Priming | 3493              |

**Comment by sdelamo** [comment]
This is now fixed since Micronaut Framework 4.3.0
