### ISSUE TITLE
Micronaut Http Handlers are appending curly brackets on static resources

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1835]
### Expected Behavior

e.g.: `<url>/swagger/<swagger-api>.yml` not to have Curly brackets in the end

Followed https://micronaut-projects.github.io/micronaut-openapi/latest/guide/#openApiViews to expose the views

### Actual Behaviour

Body is:

```
<swagger spec>
{}
```

**This only happens when deploying to AWS Lambda**, doesn't happen locally

### Steps To Reproduce

1. Create Micronaut App w/ Open API/swagger
2. Add simple controller
3. Deploy in AWS Lambda + API Gateway

### Environment Information

- Operating System: Mac OSX
- JVM: 17

### Version

4.0.3

**Comment by driverpt** [comment]
Ping

**Comment by sdelamo** [comment]
what are the steps to reproduce? After deploying to lambda what do I have to do? Do you have a sample app?

**Comment by sdelamo** [comment]
I don't reproduce the issue. I attach a sample application [projectcheckins.zip](https://github.com/micronaut-projects/micronaut-aws/files/12394004/projectcheckins.zip)

**Comment by sdelamo** [comment]
I was able to access the openAPI definition 

```
curl -i https://v1mqix9nxb.execute-api.us-east-1.amazonaws.com/prod/swagger/application.yml
HTTP/2 200 
content-type: text/plain
content-length: 362
date: Mon, 21 Aug 2023 08:29:27 GMT
x-amzn-requestid: d89f94c2-475f-4a1b-afae-9c6261cb6425
last-modified: Mon, 21 Aug 2023 10:23:30 GMT
x-amzn-remapped-content-length: 306
x-amz-apigw-id: KAIARGHroAMF7gA=
cache-control: private, max-age=60
expires: Mon, 21 Aug 2023 08:30:27 GMT
x-amzn-trace-id: Root=1-64e32067-2e2fdf9e73e6642d44b3f606;Sampled=0;lineage=e5329389:0
x-amzn-remapped-date: Mon, 21 Aug 2023 08:29:27 GMT
x-cache: Miss from cloudfront
via: 1.1 8409d1e1611b3968fdd0a92a2ea0409a.cloudfront.net (CloudFront)
x-amz-cf-pop: MAD51-C3
x-amz-cf-id: OzSv_eEjYwGzbG6-ltp0P99Pi9iuUZH9rQtkUaDJun2vWFMUEFzmig==

openapi: 3.0.1
info:
  description: My API
paths:
  /:
    get:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
```

**Comment by driverpt** [comment]
Is there anyplace I can reach you via DM ?

**Comment by driverpt** [comment]
Related to #1843
