### ISSUE TITLE
HttpRequest URI returning Path instead of full uri

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1848]
### Expected Behavior

When we add Query String arguments to the request and we need to add a Custom Header (i.e.: RFC 5988), Query String parameters do not appear

Example:
```java
@Get("/somePath")
public String foo(HttpRequest<?> request) {
   return request.getURI().toASCIIString();
}
```

This just returns "/somePath";

### Actual Behaviour

The above example only returns the path

### Steps To Reproduce

This happens also in Tests

### Version

4.0.5

**Comment by sdelamo** [comment]
I have added a test in the TCK https://github.com/micronaut-projects/micronaut-core/pull/9791

Moreover, I have started a PR with test which reproduce https://github.com/micronaut-projects/micronaut-aws/pull/1853

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-aws/pull/1853
