### ISSUE TITLE
[Bug] API GW V2 Payload setting same header on Single and MultiValue

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1858]
### Expected Behavior

If multiple, then set `multiValueHeaders`

### Actual Behaviour

Sets both `headers` and `multiValueHeaders`

### Version

4.0.3

**Comment by sdelamo** [comment]
do you have a link to AWS documentation about how single and multi behave?

**Comment by driverpt** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.response

**Comment by driverpt** [comment]
Even though its not documented, this is still used by AWS Libraries:

https://github.com/aws/aws-lambda-go/blob/main/events/apigw.go#L125-L132

**Comment by sdelamo** [comment]
I tried this in the AWS Console today. 

```
 * GET /prod/ HTTP/1.1
     * Key: value1,value2,value3
     * Foo: Bar
```

AWS instantiates : 

```
        APIGatewayProxyRequestEvent request = new APIGatewayProxyRequestEvent()
        Map<String, String> headers = new HashMap<>()
        headers.put("Foo", "Bar")
        headers.put("Key", "value1,value2,value3")
        request.setHeaders(headers)
        Map<String, List<String>> multiValueHeaders = new HashMap<>()
        multiValueHeaders.put("Key", Arrays.asList("value1", "value2", "value3"))
        multiValueHeaders.put("Foo", Collections.singletonList("Bar"))
        request.setMultiValueHeaders(multiValueHeaders)
```

**Comment by driverpt** [comment]
This issue is about the response

**Comment by sdelamo** [comment]
@driverpt what do you mean by the response? Are you not getting every header set in the micronaut HTTP response in the api gateway response ?

**Comment by timyates** [comment]
I'm going to close this for now, please open a new issue if you believe this is in error 👍
