### ISSUE TITLE
[Bug] API Gateway Payload V2: Multiple Headers with same name come as one

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1861]
### Expected Behavior

`HttpRequest<?>` to return proper Headers

### Actual Behaviour

Returns same Header with values separated by Commas

### Steps To Reproduce

```
    @Issue('https://github.com/micronaut-projects/micronaut-aws/issues/1858')
    void 'ensure multiple headers are properly received'() {
        when:
        HttpResponse<Integer> response = client.toBlocking()
                .exchange(HttpRequest.GET('/receive-multiple-headers')
                            .header(HttpHeaders.ETAG, "A")
                            .header(HttpHeaders.ETAG, "B"), Integer.class)

        then:
        response.status == HttpStatus.OK
        response.body.get() == 2
    }
```

```
        @Get(value = '/receive-multiple-headers', processes = MediaType.TEXT_PLAIN)
        Integer receiveMultipleHeaders(HttpRequest<?> request) {
            return request.headers.getAll(HttpHeaders.ETAG).size()
        }
```

### Environment Information

- Operating System: MacOS
- JVM: 17

### Version

Latest with AWS 4.0.3

**Comment by sdelamo** [comment]
we need to add a test to the core server TCK. Similar to https://github.com/micronaut-projects/micronaut-core/pull/9791

@driverpt  Do you want to contribute that PR to core?

**Comment by driverpt** [comment]
Hello,

After some digging and Testing with AWS API Gateway Payload V2, I have discovered that If a header value contains a comma, it's appended "as is".

i.e.:

```
X-SomeHeader: Foo,Bar
X-SomeHeader: Baz
```

We will have something like:
![image](https://github.com/micronaut-projects/micronaut-aws/assets/1164534/3ed13bf0-dae8-41a1-9f7e-a274fbe1bdec)


What is possibly needed is a Property that would tell the Request Converter not to split by comma in certain headers.

WDYT @sdelamo @graemerocher @timyates ?

@msailes , can you also provide some insights on this?

**Comment by sdelamo** [comment]
I just check this with Micronaut Framework 4.2.0

Sending a request such as: 

```
GET /headers HTTP/1.1
ETag: A
ETag: B
Host: pr76sk5f71.execute-api.us-east-1.amazonaws.com
Connection: close
User-Agent: RapidAPI/4.2.0 (Macintosh; OS X/13.6.1) GCDHTTPRequest
```

with a controller: 

```java
package temp1;

import io.micronaut.http.HttpHeaders;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

import java.util.Collections;
import java.util.List;
import java.util.Map;

@Controller("/headers")
public class HeadersController {

    @Get
    Map<String, List<String>> receiveMultipleHeaders(HttpRequest<?> request) {
        return Collections.singletonMap("etag" , request.getHeaders().getAll(HttpHeaders.ETAG));
    }
}
```

we get response: 

```json
HTTP/1.1 200 OK
Date: Fri, 24 Nov 2023 12:17:38 GMT
Content-Type: application/json
Content-Length: 16
Connection: close
Apigw-Requestid: O5wfYhZroAMEJlg=

{"etag":["A,B"]}
```

I am going to close this issue for now. @driverpt let me know if you think we should do any changes about this.
