### ISSUE TITLE
[BUG] Function bean with AbstractMicronautLambdaRuntime and MicronautRequestStreamHandler not working with Graalvm

### ISSUE THREAD

**Issue by swiftkoder** [micronaut-projects/micronaut-aws#1871]
### Expected Behavior

Followed the instruction to create a Java.util.Function bean with functionbean annotation and then overrode createRequestStreamHandler in AbstractMicronautLambdaRuntime.   After gradlew buildNativeLambda and updated the zip to aws, expecting lamba to run successfully. 

### Actual Behaviour

The uploaded lambda failed with 

{
  "errorMessage": "No bean of type [io.micronaut.http.client.HttpClient] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor)."
}

### Steps To Reproduce

1. Checkout sample code from https://github.com/swiftkoder/micronaut-function-bean-fail
2. run gradle buildNativeLambda
3. upload the generated native zip to aws
4. use aws lambda console test to test uploaded lambda with any payload
5. observed the error message

### Environment Information

- OSX Ventura on M1 Max

### Example Application

https://github.com/swiftkoder/micronaut-function-bean-fail

### Version

4.0.4

**Comment by sdelamo** [comment]
@swiftkoder checking this now

**Comment by sdelamo** [comment]
Add `io.micronaut:micronaut-http-client` dependency as an implementation dependency to your application.  Micronaut Framework needs an http client to poll the Lambda Runtime when you deploy as a a native executable.

**Comment by sdelamo** [comment]
what trigger do you want to use for your Lambda @swiftkoder ?

**Comment by sdelamo** [comment]
@wetted can you clarify the documentation and explicitly say users need an implementation of the Micronaut HTTP Client in the classpath when using Native Image deployment.

**Comment by swiftkoder** [comment]
Thanks for responding, i believed I tried that before and it was same thing but I will try again.  For lambda i am using a pojo payload, but the issue itself was native image not able to start due to missing http client bean.

**Comment by swiftkoder** [comment]
@sdelamo Actually if you look at my example project i already have io.micronaut:micronaut-http-client as implementation dependency.

**Comment by swiftkoder** [comment]
My example uses sqs as trigger, but you can just build image zip locally and then use aws console to pass a mock SQS payload to test easily.

**Comment by wetted** [comment]
> @wetted can you clarify the documentation and explicitly say users need an implementation of the Micronaut HTTP Client in the classpath when using Native Image deployment.

ping @sdelamo see #1891

**Comment by swiftkoder** [comment]
I did some debugging and the issue seems to be related to use of MicronautRequestStreamHandler.  If you switch to use MicronautRequestHandler then the built graalvm image works fine without complaining about missing http client bean.  In both cases the `io.micronaut:micronaut-http-client` depedency is already there.

**Comment by roamingthings** [comment]
@swiftkoder 
> I did some debugging and the issue seems to be related to use of MicronautRequestStreamHandler. If you switch to use MicronautRequestHandler then the built graalvm image works fine without complaining about missing http client bean. 

I think this is related to https://github.com/micronaut-projects/micronaut-aws/issues/1913

**Comment by swiftkoder** [comment]
Thanks for the feedback @roamingthings.  Hopefully this issue gets fix soon in near future, but I think I will revisit Micronaut later again for my team's usage when it's more stable.

**Comment by swiftkoder** [comment]
Please let me know if I should close this ticket since there is already a ticket for this issue.

**Comment by sdelamo** [comment]
@swiftkoder what is your use case? why do you want to use `MicronautRequestStreamHandler` instead of `MicronautRequestHandler`?
