### ISSUE TITLE
Duplicated query parameters in AWS Proxy Request getUri()

### ISSUE THREAD

**Issue by asantare** [micronaut-projects/micronaut-aws#1894]
### Expected Behavior

the request getUri() should return:
/path?A=1&B=2

might have been introduced in `ApiGatewayProxyServletRequest` with #1853

I didn't try a previous version, but in 3.x is working correctly (in 3.x the only method used from the AWS request is `getMultiValueQueryStringParameters`, `getQueryStringParameters` is never used)

### Actual Behaviour

the request getUri() returns:
/path?A=1&B=2&A=1&B=2

### Steps To Reproduce

1. simple AWS lambda with an hello world controller that logs the request.getUri()
2. invoke the lambda passing some query parameters

### Environment Information

- AWS lambda

### Version

4.1.1

**Comment by sdelamo** [comment]
Thanks for reporting @asantare 

This PR should fix the issue https://github.com/micronaut-projects/micronaut-aws/pull/1918
