### ISSUE TITLE
AWS Lambda invocation using Function URL not working

### ISSUE THREAD

**Issue by chufgard** [micronaut-projects/micronaut-aws#1898]
### Expected Behavior

Executing a http call against a AWS lambda function URL should not return an internal server error.
Querying the same lambda using an API Gateway works like a charm.

### Actual Behaviour

A NullPointerException is thrown:

`
Invocation with requestId [9eba27f6-956b-4e61-986f-271b2d0bdb60] failed: Name is nulljava.lang.NullPointerException: Name is null
--
at java.base@17.0.8/java.lang.Enum.valueOf(Enum.java:155)
at io.micronaut.http.HttpMethod.valueOf(HttpMethod.java:24)
at io.micronaut.function.aws.proxy.ApiGatewayServletRequest.parseMethod(ApiGatewayServletRequest.java:139)
at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyServletRequest.<init>(ApiGatewayProxyServletRequest.java:63)
`

### Steps To Reproduce

1. Deplay a lambda following this tutorial: https://guides.micronaut.io/latest/mn-serverless-function-aws-lambda-gradle-java.html
2. Enable the "Function URL" using the AWS console in the lambda's configuration section
3. Use curl to query the generated endpoint

### Version

4.0.3

**Comment by sdelamo** [comment]
when using function Url you should use `APIGatewayProxyRequestEvent`and `APIGatewayProxyResponseEvent`events: 

```
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import jakarta.inject.Inject;
import java.util.Collections;
public class FunctionRequestHandler extends MicronautRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
```

**Comment by sdelamo** [comment]
I wrote a guide to avoid this confusion in the future https://github.com/micronaut-projects/micronaut-guides/pull/1365

**Comment by sdelamo** [comment]
guide https://guides.micronaut.io/latest/mn-serverless-function-aws-lambda-function-url.html

**Comment by mikehearn** [comment]
For anyone else who lands here, the problem is that Amazon now creates API gateways with "v2" protocol to Lambda instead of v1. Set your handler to be `io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventFunction` and the NPE should go away.
