### ISSUE TITLE
MicronautRequestStreamHandler is missing ApplicationContext initialisation and startup

### ISSUE THREAD

**Issue by roamingthings** [micronaut-projects/micronaut-aws#1913]
### Expected Behavior

Lambda handler extending `MicronautRequestStreamHandler` do not fail with an error like
```
No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.function.aws.event.AfterExecutionEvent>] exists
```
and correctly inject beans into the handler class, if annotated with `@Inject`

### Actual Behaviour

The given error message appears and the handler fails unexpectedly. Fields that are annotated with `@Inject` are not initialised and therefore `null`.

### Steps To Reproduce

1. Create a simple handler class extending `MicronautRequestStreamHandler`. Throw an exception in the `execute()` method.
2. Deploy the handler
3. Invoke the handler

Comparing the implementation of `MicronautRequestStreamHandler` and `MicronautRequestHandler` I notice that the constructors of the stream handler are missing something like `injectIntoApplicationContext();` and `startEnvironment(applicationContext);`.

I'm happy to provide a pull request for this issue, if I'm not mistaken.

### Environment Information

- Java Runtime 17 on X86

### Version

4.0.5

**Comment by sdelamo** [comment]
@roamingthings Thanks I have fixed this via https://github.com/micronaut-projects/micronaut-aws/commit/426909ee1e4fbef9c674f8cc066639b67beca2a9
