### ISSUE TITLE
Regression in micronaut-function-aws-api-proxy library

### ISSUE THREAD

**Issue by nedelva** [micronaut-projects/micronaut-aws#1942]
### Expected Behavior

This issue is about single value http headers' handling by the library. 

What needs to happen: single-value http headers should be handled correctly by the ApiGatewayProxyRequestEventFunction class. 

### Actual Behaviour

Starting with version 4.0.5 of ApiGatewayProxyRequestEventFunction no longer reads single-value headers.
In the sample project provided, the test _testValidateTokenHeaderPresent_ fails for all versions in range [4.0.5,4.1.1]

### Steps To Reproduce

To reproduce, clone the project https://github.com/nedelva/demo.git and do a `mvn verify`.

### Example Application

https://github.com/nedelva/demo.git

### Version

4.1.4

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-aws/pull/1999
