### ISSUE TITLE
Improve warm start time for AWS Lambda

### ISSUE THREAD

**Issue by eugener** [micronaut-projects/micronaut-aws#199]
AWS Lambda limits resources (CPU and memory) only during `handleRequest` execution.  
It might be beneficial to move application context creation, context bean registration and injection of request handler instance out of `handleRequest` method  ( possibly into constructor ) and  leave only function execution in it. 

This seems to be already happening within `MicronautRequestStreamHandler` but not in `MicronautRequestHandler`

I can create a PR if it makes sense.

**Comment by graemerocher** [comment]
PRs welcome
