### ISSUE TITLE
Function Client AWS SDK V2

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#2121]
### Feature description

Using AWS SDK V2 for Underlying Function Client

**Comment by sdelamo** [comment]
can you elaborate what you ware requesting?

**Comment by driverpt** [comment]
Apologies. So, currently `function-client-aws` is using aws-sdk-v1, which is bringing all of the aws-sdk-v1 dependencies along everytime I use it. If you plan on using `aws-sdk-v2` exclusively, that may require extra dependencies and configurations to the projects.

TL;DR. We are requesting a `function-client-aws-v2` which is dependent exclusively on `aws-sdk-v2`.

**Comment by mbbush** [comment]
It would be great to see this released, as it would also resolve the authentication issues we're having with the current aws-sdk-v1 based `function-client-aws`, which only supports a [short list of credential providers](https://github.com/micronaut-projects/micronaut-aws/blob/b79562c8dcfaa4e1419e73f59cbf2fc0482349c5/function-client-aws/src/main/java/io/micronaut/function/client/aws/AWSLambdaConfiguration.java#L69-L73), which doesn't include what we need to run on EKS using IRSA.

I see the PR is approved; is there any estimate of when it might be merged/released?

**Comment by nathanpk-span** [comment]
Following up on @mbbush's comment -- do we have an ETA for this feature?
