### ISSUE TITLE
Load JSON Configurations from SSM 

### ISSUE THREAD

**Issue by RajeevMasseyTR** [micronaut-projects/micronaut-aws#2145]
### Issue description

At present Micronaut supports loading configuration from the SSM as showcased here [https://guides.micronaut.io/latest/micronaut-aws-parameter-store-gradle-java.html](https://guides.micronaut.io/latest/micronaut-aws-parameter-store-gradle-java.html  )

Now since there are 100's of configurations distributed what we want is we have a JSON stored in SSM at path /config  with all the configurations  

e.g 

```
{
"MCA_DOWNSTREAM_URL" : "<Some URL>",
"MCA_DOWNSTREAM_TIMEZONE" : "<Some Timezone>"
}
```

```
@ConfigurationProperties(Configurations.PREFIX)
public record Configurations(String url, String timezone) {

    public static final String PREFIX = "mca.downstream";
}

```

is there a way where we can load configuration from JSON in a SSM parameter store? and if not is there a work around?

**Comment by graemerocher** [comment]
not currently to my knowledge but it could be implemented, this is supported with consul if I recall

**Comment by RajeevMasseyTR** [comment]
So there is no work around

**Comment by RajeevMasseyTR** [comment]
Hey @graemerocher can we do something like  result = serde.readValue(ssm, COnfig.class); and load the configurations ?

**Comment by graemerocher** [comment]
Something like https://github.com/micronaut-projects/micronaut-discovery-client/blob/4.4.x/discovery-client/src/main/java/io/micronaut/discovery/consul/config/ConsulConfigurationClient.java#L192 needs implementing for SSM

**Comment by RajeevMasseyTR** [comment]
public class AwsParameterStoreConfigurationLoader extends AbstractPropertySourceLoader implements Ordered {


    private final SSMSecretManager ssmSecretManager;
    private final JsonMapper jsonMapper;
    private final Environment environment;
    private final String configurationParameterStorePath;

    /**
     * Constructs a new AwsParameterStoreConfigurationLoader.
     *
     * @param ssmSecretManager The SSM secret manager used to retrieve the configuration.
     * @param jsonMapper       The JSON mapper used to parse the configuration.
     * @param environment      The Micronaut environment to which the configuration will be added.
     * @param configurationParameterStorePath The path in SSM Parameter Store to fetch the configuration from.
     */
    public AwsParameterStoreConfigurationLoader(SSMSecretManager ssmSecretManager,
                                                JsonMapper jsonMapper,
                                                Environment environment,
                                                @Property(name = "rpc.aws.ssm.config.path") String configurationParameterStorePath) {
        super(true);
        this.ssmSecretManager = ssmSecretManager;
        this.jsonMapper = jsonMapper;
        this.environment = environment;
        this.configurationParameterStorePath = configurationParameterStorePath;
        log.trace("AwsParameterStoreConfigurationLoader constructed with path: {}", configurationParameterStorePath);
    }

    @Override
    public int getOrder() {
        log.trace("getOrder() called, returning LOWEST_PRECEDENCE");
        return Ordered.LOWEST_PRECEDENCE;
    }

    @Override
    protected void processInput(String name, InputStream input, Map<String, Object> finalMap) throws IOException {
        log.trace("processInput() called with name: {}", name);
        try {
            String jsonConfig = fetchConfigurationFromSSM();
            Map<String, Object> configMap = parseJsonConfiguration(jsonConfig);
            finalMap.putAll(configMap);
            verifyConfiguration(configMap.keySet());
        } catch (Exception e) {
            log.error("Error processing input from SSM", e);
            throw new IOException("Failed to process SSM configuration", e);
        }
    }

    private String fetchConfigurationFromSSM() throws IOException {
        log.trace("Fetching configuration from SSM at path: {}", configurationParameterStorePath);
        try {
            String jsonConfig = ssmSecretManager.getSecretValue(configurationParameterStorePath);
            log.info("Successfully retrieved configuration from SSM");
            return jsonConfig;
        } catch (Exception e) {
            log.error("Failed to retrieve configuration from SSM", e);
            throw new IOException("Error fetching configuration from SSM", e);
        }
    }

    private Map<String, Object> parseJsonConfiguration(String jsonConfig) throws IOException {
        log.trace("Parsing JSON configuration");
        try {
            Map<String, Object> configMap = jsonMapper.readValue(jsonConfig, Map.class);
            log.debug("Successfully parsed configuration map: {}", configMap);
            return configMap;
        } catch (Exception e) {
            log.error("Failed to parse JSON configuration", e);
            throw new IOException("Error parsing JSON configuration", e);
        }
    }

    private void verifyConfiguration(Set<String> requiredProperties) {
        log.trace("Verifying configuration properties");
        List<String> missingProperties = requiredProperties.stream()
                .filter(property -> !environment.containsProperty(property))
                .toList();

        if (!missingProperties.isEmpty()) {
            String errorMessage = "The following required properties are missing: " + String.join(", ", missingProperties);
            log.error(errorMessage);
            throw new IllegalStateException(errorMessage);
        }

        log.info("All required properties have been successfully loaded and verified.");
    }
} 

Would this be a solution to this issue ?

**Comment by varvay** [comment]
Any update on this issue? I actually facing a problem where I need to use a property with type of array of object. The problem is the flatten representation of it would be using index and square brackets, which is prohibited in AWS SSM. The YAML properties shown below,
```
micronaut:
  security:
    intercept-url-map:
      - pattern: /hello
        http-method: POST
        access:
          - isAnonymous()
```

This YAML properties would be equivalent to,
```
micronaut.security.intercept-url-map[0].pattern=/hello
micronaut.security.intercept-url-map[0].http-method=POST
micronaut.security.intercept-url-map[0].access[0].access=isAnonymous()
```

By enabling JSON configuration loading from SSM would also solve this issue

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-core/issues/10994
