### ISSUE TITLE
Eager Init Singletons for Lambda Handler

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#217]
I've run some tests in AWS Lambda to check the impact of Build of Micronaut Application Context  in the AWS Lambda Intialization phase and also the eager init of Singletons.

In the Intialization phase: 

- AWS Lambda starts a JVM.
- Java rutnime loads and initializes handler class.

Thus, AWS Lambda runs static initalization and the handler's constructor in the Initialization phase. 

AWS Lambda Initialization has more CPU resources than the Invocation phase. 

What I used for test is the function is the module `runtimelambdatelegram` at https://github.com/groovycalamari/exchangeratesbot  

Environment Java 11
Memory 512 MB

| Build Application Context at Initialization | Eager init singletons | Execution | Initialization    | Invocation    |
| ---------------- | -------------| ------------- | ---------- | ---------- |
| `false` | `false`                | `21.8s`                | `1.5s`                | `20.1s` 
| `false` | `true`                | `20.2s`                | `1.5s`                | `18.5s` 
| `true` | `false`                | `15.9s`                | `3.1s`                | `6.9s` 
| `true` | `true`                | `9.9s`                | `5.8s`                | `3.8s` 

I tried the same example with 3008MB and there the difference is not significant.
We are already [building the application context in the Handler constructor](https://github.com/micronaut-projects/micronaut-aws/pull/200) thanks to @eugener 

I suggest us to set default of eager init singletons to true. As the improvement performance is significant as shown in the previous table.

`io.micronaut.function.aws.MicronautRequestHandler`

```
    @Nonnull
    @Override
    protected ApplicationContextBuilder newApplicationContextBuilder() {
        ApplicationContextBuilder builder = super.newApplicationContextBuilder();
        builder.eagerInitSingletons(eagerInitSingletons);
        builder.environments(ENVIRONMENT_LAMBDA);
        return builder;
    }
```

Eager init of singletons is only available at micronaut 2.0

**Comment by graemerocher** [comment]
This has to go into 2.0.0 and will require Micronaut 2.0
