### ISSUE TITLE
Exception Handlers not run in AWS API Gateway

### ISSUE THREAD

**Issue by rnielsen** [micronaut-projects/micronaut-aws#22]
Exception Handlers are not run when Micronaut is run through API Gateway integration.   Any exceptions that occur return a 502 Gateway Timeout to the client.

This affects custom error handlers as well as @Valid annotations

Example project at https://github.com/rnielsen/micronaut-aws-apiproxy-test
```
curl -i http://localhost:8080/test/exception
HTTP/1.1 200 OK

Exception Handled
```

```
curl -i https://3kf8ik2za4.execute-api.ap-southeast-2.amazonaws.com/dev/test/exception
HTTP/2 502 

{"message":"Gateway timeout"}
```
Tested against io.micronaut.aws:micronaut-function-aws-api-proxy:1.1.0.RC3"

**Comment by rnielsen** [comment]
Thanks.  Looks better, although CORS headers are not included when exceptions occur
```
curl -i -H "Origin:test" http://localhost:8080/test/exception
HTTP/1.1 200 OK
Access-Control-Allow-Origin: test
Access-Control-Allow-Credentials: true

Exception Handled
```
```
curl -i -H "Origin:test" https://3kf8ik2za4.execute-api.ap-southeast-2.amazonaws.com/dev/test/exception
HTTP/2 200 

Exception Handled
```

**Comment by graemerocher** [comment]
@rnielsen could you raise an separate issue for that.. thx

**Comment by rnielsen** [comment]
@graemerocher done - [#25](https://github.com/micronaut-projects/micronaut-aws/issues/25)
