### ISSUE TITLE
In Lambda custom runtimes propagate the tracing header (Lambda-Runtime-Trace-Id) to env. _X_AMZN_TRACE_ID

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#234]
One of the steps described in [Custom AWS Lambda Runtimes](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html): 

> Propagate the tracing header – Get the X-Ray tracing header from the Lambda-Runtime-Trace-Id header in the API response. Set the _X_AMZN_TRACE_ID environment variable with the same value for the X-Ray SDK to use.

[Setting Environment variables](https://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java) in Java is not supported and I don't think we should use any of the hack workarounds.

Moreover it seems AWS XRAY SDK does not support it either. 

https://github.com/aws/aws-xray-sdk-java/issues/102

**Comment by OlehTsivanTR** [comment]
Hi, it looks like we can propagate it through the 'setProperty()' now. Could we consider this approach?

https://github.com/aws/aws-xray-sdk-java/pull/252

**Comment by sdelamo** [comment]
thanks @OlehTsivanTR I am going to check it.
