### ISSUE TITLE
FunctionInitializer does not parse @JsonProperty

### ISSUE THREAD

**Issue by scarlier** [micronaut-projects/micronaut-aws#30]
while using micronaut version 1.1

When using the FunctionInitializer the Pojo that is parsed with jackson does not read the @JsonProperties annotation.

*Json*
```
{
    "Records": ["test1", "test2"]
}
```

*Pojo*
```
@Introspected
public class SqsEvent {

   @JsonProperty("Records")
    private List<String> records;

    public List<String> getRecords() {
        return records;
    }

    public void setRecords(List<String> records) {
        this.records = records;
    }
}
```

*function*
```
@Singleton
public class SqsFunction extends FunctionInitializer {
    
    public void execute(SqsEvent event) {
       event.getRecords(); // is always empty
    }
}
```

while using ObjectMapper directly it works
```
SqsEvent event = mapper.readValue(json, SqsEvent.class);
event.getRecords(); // is filled
```

**Comment by graemerocher** [comment]
The reason for this when deployed in this manner. It is AWS deserializes the POJO not Micronaut. Do you have any custom Jackson logic somewhere?

**Comment by scarlier** [comment]
Ok. Found out that the proper way is to use `io.micronaut.function.aws.MicronautRequestStreamHandler::handleRequest`, when there is need for custom deserialisation.
