### ISSUE TITLE
Will the DynamoDB functionality be available in the M1 release?

### ISSUE THREAD

**Issue by ddelponte** [micronaut-projects/micronaut-aws#323]
@alvarosanchez I see you've recently committed some code in support of DynamoDB. 😃 

Do you know if this functionality will be available in the M1 release or a BUILD-SNAPSHOT?

Thanks!

**Comment by alvarosanchez** [comment]
It is already available in the published 2.0.0.BUILD-SNAPSHOT. Check [the documentation about how to use snapshot versions](https://docs.micronaut.io/latest/guide/index.html#usingsnapshots).

And of course, it will be part of the upcoming 2.0.0 release.
