### ISSUE TITLE
AWS API Gateway Support - Example application Link is not working

### ISSUE THREAD

**Issue by avanishranjan** [micronaut-projects/micronaut-aws#33]
The link to Example application https://github.com/micronaut-projects/micronaut-aws/tree/master/examples/api-proxy-example responds with 404.

**Comment by marceloverdijk** [comment]
Currently the `AWS API Gateway Support` section in the latest docs refer to the example https://github.com/micronaut-projects/micronaut-aws/tree/master/examples/api-gateway-example which is available. 
I think this issue can be closed.
