### ISSUE TITLE
HttpResponse not working properly inside lambda environment using graalvm

### ISSUE THREAD

**Issue by traycho** [micronaut-projects/micronaut-aws#341]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Follow steps from https://bitbucket.org/traycho/micronaut-examples/src/master/

1. application
2. Run it in sam local environment
3. Execute curl -G http://localhost:3000/ping

### Expected Behaviour

Application should behave same running standard jar or graalvm compiled binary.
Executing curl -G http://localhost:3000/ping should result into { "message": "ping"}

### Actual Behaviour

Executing curl -G http://localhost:3000/ping results into {}
Using HttpResponse returned by controller methods results into {} empty body.

### Environment Information

- **Operating System**: MacOs Sierra
- **Micronaut Version:** 1.3.6
- **JDK Version:** 1.8.0_222
- **aws sam cli :** 0.47.0

### Example Application

Checkout code from
https://bitbucket.org/traycho/micronaut-examples/src/master/

**Comment by traycho** [comment]
Reopned from https://github.com/micronaut-projects/micronaut-aws/issues/105

**Comment by graemerocher** [comment]
most probably an issue with interaction with lombok

**Comment by traycho** [comment]
Just tried removing the lombok, same result.

**Comment by traycho** [comment]
Confirm adding concrete version 1.4.0 is solving the issue 
io.micronaut.aws:micronaut-function-aws-api-proxy:1.4.0

Closing the ticket.
