### ISSUE TITLE
Support disabling System Manager Parameter Store queries by micronaut environment

### ISSUE THREAD

**Issue by sam-lewis** [micronaut-projects/micronaut-aws#376]
The start-up performance of my AWS lambda function is negatively impacted by the number of requests to System Manager Parameter Store.

Currently paths for every active micronaut profile are queried e.g.
- `/config/application`
- `/config/myapp`
- `/config/application_EC2`
- `/config/myapp_EC2`
- `/config/application_lambda`
- `/config/myapp_lambda`
- etc etc

I would like the ability to only query paths `/config/application` and`/config/myapp`.

This could be achieved with a new property `aws.client.system-manager.parameterstore.searchActiveEnvironments` which defaults to true in order to preserve existing behaviour.

I have been testing this in a fork and can open a pull request if desirable.

**Comment by graemerocher** [comment]
Seems like a good idea, PRs welcome

**Comment by sam-lewis** [comment]
Thanks @graemerocher I opened a draft PR
