### ISSUE TITLE
Escaped json response from micronaut-graphql when use with micronaut-function-aws-api-proxy

### ISSUE THREAD

**Issue by limcheekin** [micronaut-projects/micronaut-aws#392]
Hi there,

### Steps to Reproduce
1. Create more data by posting the following json to the AWS lambda URL:
https://0wkpgk7b07.execute-api.ap-southeast-1.amazonaws.com/Prod/people
```
{
    "firstName": "John",
    "lastName": "Doe",
    "gender": "MALE"
}
```
Then, it will response:
```
{
    "id": 1,
    "firstName": "John",
    "lastName": "Doe",
    "age": 0,
    "gender": "MALE"
}
```
2. Retrieve the data by posting the following json the GraphQL endpoint with content type `application/json`:
https://0wkpgk7b07.execute-api.ap-southeast-1.amazonaws.com/Prod/graphql
```
{
  "query":"{ findById(id: 1) { lastName firstName gender } }"
}
```
Then, it will response:
```
[
    "{\"data\":{\"findById\":{\"lastName\":\"Doe\",\"firstName\":\"John\",\"gender\":\"MALE\"}}}"
]
```
You can see that the json response is escaped.

### Expected Behaviour
When it run locally it response correctly with different structure compares to the escaped one:
```
{
    "data": {
        "findById": {
            "lastName": "Doe",
            "firstName": "John",
            "gender": "MALE"
        }
    }
}
```
The endpoint should response JSON similar to above instead of escaped one.

### Environment Information
The project can run locally without database.

### Example Application
I created a github repo for you to re-produce the issue at **master** branch of https://github.com/limcheekin/micronaut-person

**Comment by limcheekin** [comment]
The issue doesn't happened in the following version of Micronaut:
```
micronautVersion=1.2.11
```

Hence, I downgraded it from the following version to keep the ball rolling:
```
micronautVersion=2.0.0
```

**Comment by sdelamo** [comment]
Several things about your sample code: 

- You no longer need to annoate your controllers with @Validated

- You can delete the class StreamLambdaHandler. You can use directly `io.micronaut.function.aws.proxy.MicronautLambdaHandler` as your handler. 


When workign with Lambdas it is important to keep dependencies in your main classpath to a minimum. 

- You should not include the http-server-netty dependency. 

Delete: 

```groovy
    implementation "io.micronaut:micronaut-http-server-netty"
```

- Move http-client to testImplementation. 

instaed of: 

```groovy

    implementation "io.micronaut:micronaut-http-client"
```

use: 

```groovy
    testImplementation "io.micronaut:micronaut-http-client"
```


- You should write your tests against the LambdaHandler not the embedded server. So that your tests are testing the real app. I have rewritten your tests here: 

```java

public class PersonControllerTest {
    private static MicronautLambdaHandler handler;
    private static Context _lambdaContext_ = new MockLambdaContext();
    private static ObjectMapper objectMapper;

    @BeforeAll
    public static void setupSpec() {
        try {
            handler_ = new MicronautLambdaHandler();
            objectMapper = _handler_.getApplicationContext().getBean(ObjectMapper.class);

        } catch (ContainerInitializationException e) {
            e.printStackTrace();
        }
    }

    @AfterAll
    public static void cleanupSpec() {
        handler.getApplicationContext().close();
    }

    private AwsProxyRequest postRequest(String path, Object body) throws JsonProcessingException {
        String json = (body instanceof String) ? ((String) body) : _objectMapper_.writeValueAsString(body);
        return new AwsProxyRequestBuilder(path, HttpMethod.POST.toString())
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                .body(json)
                .build();
    }

    private Person validPerson() {
        Person person = new Person();
        person.setFirstName("John");
        person.setLastName("Smith");
        person.setAge(33);
        person.setGender(Person.Gender.MALE);
        return person;
    }

    @Test
    public void testAddNotValid() throws Exception {
        Person person = validPerson();
        person.setAge(-1);
        AwsProxyRequest request = postRequest("/people", person);
        AwsProxyResponse response = handler.handleRequest(request, lambdaContext);
        assertEquals(HttpStatus.BAD_REQUEST.getCode(), response.getStatusCode());
        assertTrue(response.getBody().contains("person.age: must be greater than or equal to 0"));
    }
}
```

I have created PR against your sample project:

https://github.com/limcheekin/micronaut-person/pull/1

**Comment by sdelamo** [comment]
@limcheekin I am not able to reproduce your issue with your sample appplication. 

However, I think version 2.0.3 of Micronaut AWS may contain a fix for your problem. Coud you try with 2.0.3 and confirm it is fixed. 

```groovy
repositories {
    mavenCentral()
    jcenter()

    maven {
        url 'https://dl.bintray.com/micronaut/core-releases-local'
    }
}
...
configurations.all {
    resolutionStrategy {
        force 'io.micronaut.aws:micronaut-aws-common:2.0.3'
        force 'io.micronaut.aws:micronaut-function-aws:2.0.3'
        force 'io.micronaut.aws:micronaut-function-aws-api-proxy:2.0.3'
    }
}
```

Please, reopen if the issue is still unsolved.

**Comment by limcheekin** [comment]
Yes, you suggestion resolved the issue. 👍 
 
You can't re-produced the issue again using the steps above as I deployed the code of the branch which using previous version Micronaut which don't have such issue.
