### ISSUE TITLE
(AWS Lambda) Exception Handler invocation is non-deterministic  

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-aws#41]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Implement a class derived from RuntimeException and a corresponding exception handler for the specific subclass.
2. Also implement an exception handler for RuntimeException
3. Throw the derived class in an HTTP request handler
4. Deploy to AWS Lambda (using the Lambda proxy from Micronaut)
5. Invoke the HTTP request handler

### Expected Behaviour

The exception handler for the derived exception is always invoked.

### Actual Behaviour

Sometimes, apparently "at random" the RuntimeException handler is invoked.

### Environment Information

AWS Lambda (Java 8, standard AWS runtime)

### Example Application

https://github.com/alexwilbur/mn-issues

**Comment by graemerocher** [comment]
I believe this line https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java#L260

Should use `byTypeArgumentsClosest` like 

https://github.com/micronaut-projects/micronaut-core/commit/767381412b409dcfc5ddd36322169ae551ced16a#diff-0f91f8567f30707e6e437d24f3109b89R323

**Comment by mzouitni** [comment]
Any idea when this bug will be fixed? Any workaround for the time being?

**Comment by alexwilbur** [comment]
We haven't found a workaround for this :(

**Comment by mzouitni** [comment]
I managed to make it work by adding @Primary on the custom exception handler

**Comment by alexwilbur** [comment]
Nice! I will try that :) Thanks!

**Comment by alexwilbur** [comment]
@graemerocher  any possibility of a release of 1.2.0 ?

**Comment by graemerocher** [comment]
Will have a look soon. Thanks
