### ISSUE TITLE
Feature aws-api-gateway used in docs doesn't exist

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-aws#412]
This doc https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#apiProxy shows:

> An alternative approach to using Micronaut with AWS is to use Micronaut support for the AWS Serverless Java Container project.
Using the CLI with Micronaut 1.1 or above
$ mn create-app my-app --features aws-api-gateway

But the `aws-api-gateway` feature doesn't exist.

**Comment by anilokta** [comment]
Any update on this issue?

**Comment by sdelamo** [comment]
I've re-written the Lambda docs. It links to several guides about AWS Lambda and Micronaut 2.

https://micronaut-projects.github.io/micronaut-aws/snapshot/guide/index.html#lambda
