### ISSUE TITLE
create-function command doesn't exist

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-aws#413]
From: https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#lambda

> Regular Micronaut functions created via mn create-function can be deployed to Lambda directly.
 Using the CLI
$ mn create-function example

`create-function` command doesn't exist.

**Comment by sdelamo** [comment]
I have update the [Lambda documentation](https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#lambda).
