### ISSUE TITLE
AWS SNS Event is not being deserialised correctly

### ISSUE THREAD

**Issue by malysz** [micronaut-projects/micronaut-aws#459]
Hi, I'm trying to use Micronaut 2.0.0 with AWS Lambda and SNS Event as an input and it looks like my SNS Event is not being deserialised and the sns record is empty.

The code I use: 
```java
public class LambdaFunction extends MicronautRequestHandler<SNSEvent, Long> {
    @Override
    public Long execute(SNSEvent input) {
        List<SNSEvent.SNSRecord> records = input.getRecords();
        logger.info("Records no: {}", records.size());
        SNSEvent.SNSRecord snsRecord = records.get(0); // this is empty
        logger.info("Record: {}", snsRecord);
        return 1L;
    }
}
```

Project uses lambda-events:
```xml
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-core</artifactId>
    <version>1.2.1</version>
</dependency>
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-events</artifactId>
    <version>3.1.0</version>
</dependency>
```

### Expected Behaviour

I should be able to get message from SNS Event JSON (sample below): 
```json
{
  "Records": [
    {
      "EventVersion": "1.0", 
      "EventSubscriptionArn": "arn:aws:sns:EXAMPLE", 
      "EventSource": "aws:sns", 
      "Sns": {
        "Signature": "EXAMPLE", 
        "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e", 
        "Type": "Notification", 
        "TopicArn": "arn:aws:sns:EXAMPLE", 
        "MessageAttributes": {
          "Test": {
            "Type": "String", 
            "Value": "TestString"
          }, 
          "TestBinary": {
            "Type": "Binary", 
            "Value": "TestBinary"
          }
        }, 
        "SignatureVersion": "1", 
        "Timestamp": "2015-06-03T17:43:27.123Z", 
        "SigningCertUrl": "EXAMPLE", 
        "Message": "Hello from SNS!", 
        "UnsubscribeUrl": "EXAMPLE", 
        "Subject": "TestInvoke"
      }
    }
  ]
}
```

### Actual Behaviour

```
INFO main - LambdaFunction:41 - Records no: 1
INFO main - LambdaFunction:42 - Record: {}
```

### Environment Information

- **Operating System**: linux (AWS Lambda)
- **Micronaut Version:** 2.0.0
- **JDK Version:** Java 11 (Corretto)

**Comment by cassadyj** [comment]
I am unable to reproduce the actual results above.  When an SNS Event is provided to the Lambda function, the message is parsed correctly.  Tested with the Lambda test utility as well as an even published from an SNS Topic.

If this is still an issue for you, provide more information about your Lambda function, how it is configured and permissions allowed.

**Comment by fpinto-chwy** [comment]
> Hi, I'm trying to use Micronaut 2.0.0 with AWS Lambda and SNS Event as an input and it looks like my SNS Event is not being deserialised and the sns record is empty.
> 
> The code I use:
> 
> ```java
> public class LambdaFunction extends MicronautRequestHandler<SNSEvent, Long> {
>     @Override
>     public Long execute(SNSEvent input) {
>         List<SNSEvent.SNSRecord> records = input.getRecords();
>         logger.info("Records no: {}", records.size());
>         SNSEvent.SNSRecord snsRecord = records.get(0); // this is empty
>         logger.info("Record: {}", snsRecord);
>         return 1L;
>     }
> }
> ```
> 
> Project uses lambda-events:
> 
> ```
> <dependency>
>     <groupId>com.amazonaws</groupId>
>     <artifactId>aws-lambda-java-core</artifactId>
>     <version>1.2.1</version>
> </dependency>
> <dependency>
>     <groupId>com.amazonaws</groupId>
>     <artifactId>aws-lambda-java-events</artifactId>
>     <version>3.1.0</version>
> </dependency>
> ```
> 
> ### Expected Behaviour
> I should be able to get message from SNS Event JSON (sample below):
> 
> ```json
> {
>   "Records": [
>     {
>       "EventVersion": "1.0", 
>       "EventSubscriptionArn": "arn:aws:sns:EXAMPLE", 
>       "EventSource": "aws:sns", 
>       "Sns": {
>         "Signature": "EXAMPLE", 
>         "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e", 
>         "Type": "Notification", 
>         "TopicArn": "arn:aws:sns:EXAMPLE", 
>         "MessageAttributes": {
>           "Test": {
>             "Type": "String", 
>             "Value": "TestString"
>           }, 
>           "TestBinary": {
>             "Type": "Binary", 
>             "Value": "TestBinary"
>           }
>         }, 
>         "SignatureVersion": "1", 
>         "Timestamp": "2015-06-03T17:43:27.123Z", 
>         "SigningCertUrl": "EXAMPLE", 
>         "Message": "Hello from SNS!", 
>         "UnsubscribeUrl": "EXAMPLE", 
>         "Subject": "TestInvoke"
>       }
>     }
>   ]
> }
> ```
> 
> ### Actual Behaviour
> ```
> INFO main - LambdaFunction:41 - Records no: 1
> INFO main - LambdaFunction:42 - Record: {}
> ```
> 
> ### Environment Information
> * **Operating System**: linux (AWS Lambda)
> * **Micronaut Version:** 2.0.0
> * **JDK Version:** Java 11 (Corretto)

I'm experiencing the same issue above. Was this issue addressed and/or a solution provided?

**Comment by sdelamo** [comment]
@fpinto-chwy can you provide a sample app. I have this Micronaut Lambda Handler which consumes a SNS and it works fine: https://github.com/microchatbots/lambdal337sns
