### ISSUE TITLE
Ensure all AWS events are registered for reflection and work in Native Image

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-aws#493]
Not all AWS events work on native image. We need to fix that.

**Comment by charlie-harvey** [comment]
How difficult is this task? Can it be done by looking at previous examples? I would be happy to work on it - really love what you are doing here and want to help.

**Comment by pgressa** [comment]
#944 should fix this.

**Comment by charlie-harvey** [comment]
It seems that all the classes in the aws-sdk get parsed. But what about all the classes in the `aws-lambda-java-events`? That's where the `SQSEvent` and others live.
