### ISSUE TITLE
Incoming Cookies not available in AWS API Gateway

### ISSUE THREAD

**Issue by rnielsen** [micronaut-projects/micronaut-aws#50]
Incoming Cookies are not available via `httpRequest.getCookies()` when Micronaut is run through API Gateway integration.  Outgoing cookies are added to the response correctly and the cookies are available via `httpRequest.getHeaders().get("Cookie")`

The specific issue affecting me is that Micronaut JWT authentication via Cookies is not allowing access to secured pages after login.

Example project at https://github.com/rnielsen/micronaut-aws-apiproxy-test
```
curl -i --cookie test=value http://localhost:8080/test/checkCookies
HTTP/1.1 200 OK

{"cookieHeader":"test=value","cookies":[{"nettyCookie":{"secure":false,"httpOnly":false},"name":"test","value":"value","secure":false,"maxAge":-9223372036854775808,"httpOnly":false}]}
```

```
curl -i --cookie test=value https://3kf8ik2za4.execute-api.ap-southeast-2.amazonaws.com/dev/test/checkCookies
HTTP/2 200 

{"cookieHeader":"test=value"}
```
Tested against io.micronaut.aws:micronaut-function-aws-api-proxy:1.1.3.BUILD-SNAPSHOT"

**Comment by kastork** [comment]
Problem exists in 1.2.0 also

**Comment by kastork** [comment]
@rnielsen  A workaround...
(Kotlin)

```kotlin
@Singleton
@Replaces(JwtCookieTokenReader::class)
class GatewayJwtCookieTokenReader(
	@Inject private val jwtCookieConfiguration: JwtCookieConfiguration
) : TokenReader {

	override fun findToken(request: HttpRequest<*>): Optional<String> {
		val headers: MutableList<String>? = request.headers.getAll(HttpHeaders.COOKIE)
		val header = headers?.firstOrNull() { it.split("=")[0] == jwtCookieConfiguration.cookieName }

		return if (header != null) {
			val cookieValue = header.split("=")[1]
			Optional.of(cookieValue)
		} else {
			Optional.empty<String>()
		}
	}

	override fun getOrder(): Int {
		return 0
	}
}
```

**Comment by rnielsen** [comment]
Thanks @kastork. I worked around it with a HttpServerFilter to populate request.getCookies() from the header.
