### ISSUE TITLE
Multipart file uploads do not work with AWS API Gateway

### ISSUE THREAD

**Issue by tobiasbayer** [micronaut-projects/micronaut-aws#53]
I have a route for a multipart file upload which works fine when running the service as a standalone application:

```
    @Post("/attachments", consumes = [MediaType.MULTIPART_FORM_DATA])
    fun uploadImage(file: CompletedFileUpload) : HttpResponse<Any> {
        ...
        return HttpResponse.created("Created")
    }
```

When testing the route with `curl -v -X POST http://localhost:8080/attachments -H 'Content-type: multipart/form-data' -F file=@/path/image.jpg` everything works fine.

When I deploy the service as a Lambda with API Gateway access, the file does not seem to make it to the controller: `io.micronaut.web.router.exceptions.UnsatisfiedRouteException: Required argument [CompletedFileUpload file] not specified`.

All other routes in my application work correctly even if deployed to AWS Lambda + API Gateway so I suspect there might be an issue with parsing the API Gateway input in the Micronaut AWS Proxy Handler.

**Comment by musketyr** [comment]
API Gateway is not very friendly about file uploads or binary formats in general. You may try uploading directly to S3 instead. You can use STS for this.

There is a service for STS in out Micronaut Libraries: 
https://github.com/agorapulse/micronaut-libraries/blob/master/micronaut-aws-sdk/src/main/groovy/com/agorapulse/micronaut/aws/sts/SecurityTokenService.java

Here's an article about direct S3 uploads (no Micronaut I hope you can figure it out):
https://medium.com/@ashan.fernando/upload-files-to-aws-s3-using-signed-urls-fa0a0cf489db

**Comment by tobiasbayer** [comment]
Thanks, @musketyr
