### ISSUE TITLE
MicronautLambdaHandler returns invalid response in SAM local

### ISSUE THREAD

**Issue by kastork** [micronaut-projects/micronaut-aws#544]
This might be a very specific situation, but it seems like this should "just work"

When using the AWS CDK to generate a lambda/api-gateway application, you can now generate a local `template.yaml` and run it locally with the SAM cli. I've done this and it seems like a nice way to do this sort of thing, but I've run into a problem that may or may not be Micronaut related.

I've attached a project with a detailed readme to assist with replicating the problem.  I won't repeat the whole readme here, but the crux of it is that invoking a POST endpoint in a "proxy"-style app returns a malformed lambda response so you just get a "BadGateway".

[mn-cdk-sam-reproducer.zip](https://github.com/micronaut-projects/micronaut-aws/files/5288781/mn-cdk-sam-reproducer.zip)

The problem is the response object contains the key `base64Encoded` instead of the required `isBase64Encoded`.

```
Invalid lambda response received: Invalid API Gateway Response Keys: {'base64Encoded'} in {'statusCode': 200, 'multiValueHeaders': {'Content-Type': ['application/json']}, 'body': '{"name":"foo","isbn":"32d63efa-fe08-409b-a5d2-9105586f1770"}', 'base64Encoded': False}
2020-09-27 10:31:22 127.0.0.1 - - [27/Sep/2020 10:31:22] "POST /book HTTP/1.1" 502 -

```

**Comment by kastork** [comment]
I'm now less convinced this has to do with Micronaut.  When deployed to AWS, the project works as expected.

```
› http POST https://uu5dplmknj.execute-api.us-west-2.amazonaws.com/prod/book name=foo
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 60
Content-Type: application/json
Date: Sun, 27 Sep 2020 21:02:31 GMT
Via: 1.1 8d457183fa243dba1db74aa77399e24b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HIfISHAEERYNUUElVCrT_iO8oowKsP5BZbktcy9B1zzJphZwYYgPiw==
X-Amz-Cf-Pop: LAX50-C1
X-Amzn-Trace-Id: Root=1-5f70fddf-859ff4f829ce5310497d3e90;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: Tiya4EmVPHcFbbQ=
x-amzn-RequestId: 1aa0a286-af38-4cb8-9e99-c3748e9d8d8c

{
    "isbn": "43094531-6441-4f0a-811c-76a4e3dcfd3a",
    "name": "foo"
}
```

I'll look into issue over at the SAM cli project.

**Comment by kastork** [comment]
Related issues.  It seems nobody is willing to own this.

https://github.com/awslabs/aws-serverless-java-container/issues/262#

https://github.com/aws/aws-sam-cli/issues/1193#issuecomment-495004163

**Comment by graemerocher** [comment]
Seems like a bug in SAM if it only occurs there

**Comment by alvarosanchez** [comment]
Closing as per previous comments
