### ISSUE TITLE
application/json should be a default content type

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-aws#60]
API Gateway assumes that the endpoints accept/produce JSON objects. This should be the default for MIcronaut as well. Currently, for example, if you are missing the `Content-Type` header then `@Body` objects are not populated correctly.

**Comment by peterschunk1** [comment]
Agree this is very confusing if you consider that other frameworks make this assumption and don't fail with a confusing error message that no body was provided.
