### ISSUE TITLE
Parameter Store queries could use some configurability

### ISSUE THREAD

**Issue by ttzn** [micronaut-projects/micronaut-aws#657]
As stated in the documentation [here](https://docs.micronaut.io/latest/guide/index.html#distributedConfigurationAwsParameterStore), the `AWSParameterStoreConfigClient` will send queries for a number of paths computed from the application name and the active environments, following a fixed format. In one of my projects, an application needed to access values written by a configuration publishing pipeline on a path prefix over which I had no control. Playing with the `rootHierarchyPath` can help but in this case `/rootHierarchyPath/application` was off-limits and the client crashed with an `AccessDeniedException`. I had to override the entire client to get things to work and integrate properly with the `PropertySource` machinery. I am sure there are many other situations where more flexibility would be needed.

Maybe we can extract the path calculation in a dedicated component with an exposed interface, and provide users with a way to configure the target paths as they please by implementing it. The default implementation would preserve the current behaviour. What do you think ? I am ready to make a PR.

**Comment by graemerocher** [comment]
PRs welcome!
