### ISSUE TITLE
AWS Lambda Custom Runtimes example missing in repo

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-aws#77]
The latest docs regarding using `Custom GraalVM Native Runtimes` mention the example application: https://github.com/micronaut-projects/micronaut-aws/tree/master/examples/api-proxy-graal-custom-runtime-example

But this example is actually not in the repo.

**Comment by graemerocher** [comment]
An example can be found here in the meantime https://github.com/awslabs/aws-serverless-java-container/tree/micronaut/samples/micronaut/pet-store
