### ISSUE TITLE
AWS Lambda Custom Runtimes problem

### ISSUE THREAD

**Issue by ybulbuk** [micronaut-projects/micronaut-aws#80]
I create an app using CLI command:
`mn create-app my-app --features aws-api-gateway-graal --build maven`

After I build a jar file, I'm trying to run it using generated `deploy.sh` file.

Trying to call a Lambda i'm constantly got:

> No bin/java and no environment variable JAVA_HOME

**Comment by musketyr** [comment]
I had the exactly same problem which is gone after upgrading to Micronaut 1.2.4 stack
