### ISSUE TITLE
Request reader does not take into account produces mediatype

### ISSUE THREAD

**Issue by kristofvb** [micronaut-projects/micronaut-aws#868]
`io.micronaut.function.aws.proxy.MicronautRequestReader#readRequest` selects the route without matching the Accept content type passed by the client with the produces content type of the selected controller method(s).

### Steps to Reproduce

Consider a controller with the following methods

```
    @Get(value = "/ok", produces = MediaType.APPLICATION_JSON)
    public String getOkAsJson() {
        return "{\"status\":\"ok\"}";
    }

    @Get(value = "/ok", produces = MediaType.TEXT_HTML)
    public String getOkAsHtml() {
        return "<div>ok</div>";
    }
```
If a client makes a call and specifies the Accept header it will always return the content produced by the first method, in this case the method producing JSON.

### Expected Behaviour

I expect method `io.micronaut.function.aws.proxy.MicronautRequestReader#readRequest` to return content matching the requested content type.

### Actual Behaviour

Client always receives content produced by the first method matching the request path without taking into account Accept header.

### Environment Information

- **Operating System**: macos
- **Micronaut Version:** 2.2.0
- **Micronaut AWS Version:** 2.2.3
- **JDK Version:** 11

**Comment by ttzn** [comment]
Confirmed. `MicronautRequestReader ` calls `DefaultRouter#find()` and returns the first match between many, while the Netty `RoutingInBoundHandler` uses `findAllClosest` which does filter based on the `Accept` header, and fails in case of multiple matches. Should be easy to streamline, unless there is a good reason for the AWS handler not to have this capability.
