### ISSUE TITLE
New artifact io.micronaut.aws:micronaut-function-aws-test not in micronaut BOM

### ISSUE THREAD

**Issue by athkalia** [micronaut-projects/micronaut-aws#890]
Hello,

It seems like while the new sub-project that contains the new `@MicronautLambdaTest` annotation is available (`io.micronaut.aws:micronaut-function-aws-test:2.3.0`), it's not part of the Micronaut BOM, so you need to declare it's version to import it. 

The BOM for `2.3.0` is [here](https://repo1.maven.org/maven2/io/micronaut/micronaut-bom/2.3.0/micronaut-bom-2.3.0.pom)

**Comment by ttzn** [comment]
My bad, update submitted
