### ISSUE TITLE
Cannont build native image with AWS param store due to io.micronaut.discovery.client.DnsResolver

### ISSUE THREAD

**Issue by LtTempletonPeck** [micronaut-projects/micronaut-aws#898]
I am unable to build a native image when the AWS param store dependency `io.micronaut.aws:micronaut-aws-parameter-store` is added to a lambda project due to the build time initialisation of the `DNSResolver`

This can be overcome by adding a runtime initialisation on to the gradle build for the `DnsResolver` class

```
    nativeImage {
        args("--initialize-at-run-time=io.micronaut.discovery.client.DnsResolver")
    }
```

@ilopmar suggested on Gitter
>  Maybe we need to delay to runtime some class initialization in micronaut-aws

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. clone https://github.com/LtTempletonPeck/aws-parm-store/tree/main
2. `./gradlew nativeImage`

### Expected Behaviour

The native image should build successfully

### Actual Behaviour

Native image fails with
```
Error: Classes that should be initialized at run time got initialized during image building:
 com.sun.jndi.toolkit.ctx.PartialCompositeDirContext was unintentionally initialized at build time. To see why com.sun.jndi.toolkit.ctx.PartialCompositeDirContext got initialized use --trace-class-initialization=com.sun.jndi.toolkit.ctx.PartialCompositeDirContext
com.sun.jndi.toolkit.ctx.PartialCompositeContext was unintentionally initialized at build time. To see why com.sun.jndi.toolkit.ctx.PartialCompositeContext got initialized use --trace-class-initialization=com.sun.jndi.toolkit.ctx.PartialCompositeContext
com.sun.jndi.dns.DnsContext was unintentionally initialized at build time. To see why com.sun.jndi.dns.DnsContext got initialized use --trace-class-initialization=com.sun.jndi.dns.DnsContext
com.sun.jndi.toolkit.ctx.ComponentDirContext was unintentionally initialized at build time. To see why com.sun.jndi.toolkit.ctx.ComponentDirContext got initialized use --trace-class-initialization=com.sun.jndi.toolkit.ctx.ComponentDirContext
com.sun.jndi.toolkit.ctx.AtomicContext was unintentionally initialized at build time. To see why com.sun.jndi.toolkit.ctx.AtomicContext got initialized use --trace-class-initialization=com.sun.jndi.toolkit.ctx.AtomicContext
com.sun.jndi.toolkit.ctx.ComponentContext was unintentionally initialized at build time. To see why com.sun.jndi.toolkit.ctx.ComponentContext got initialized use --trace-class-initialization=com.sun.jndi.toolkit.ctx.ComponentContext
```

### Environment Information

- **Operating System**: linux
- **Micronaut Version:** 2.3.0
- **JDK Version:** 11

**Comment by pgressa** [comment]
@LtTempletonPeck make sure you're running Micronaut 2.3.0 with GraalVM 21.0.0, plus to eliminate stale classes, run the `clean` task

**Comment by LtTempletonPeck** [comment]
@pgressa I am and I do. Are you saying it works for you?

**Comment by ilopmar** [comment]
@LtTempletonPeck I'm able to reproduce the issue. I'll add the runtime initialization to the micronaut-discovery-client module and release a new version. 
In the mean time you can keep the workaround.
