### ISSUE TITLE
AWS lambda can not build S3 Client

### ISSUE THREAD

**Issue by ivansynyshynkindgeek** [micronaut-projects/micronaut-aws#915]
Hello

I'm working on AWS lambda that should upload files to S3 bucket. Locally it works fine but when I build native image using Docker and deploy it to AWS lambda there is a problem to build S3Clien. Function to build S3Client looks like:

``` 
AmazonS3 s3Client = AmazonS3ClientBuilder
                .standard()
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(this.accessKeyId, this.secretKey)))
                .withRegion(Regions.EU_CENTRAL_1)
                .build();
```

this.accessKeyId, this.secretKey - valid values for credentials

Stracktrace looks like:

``` 
com.amazonaws.SdkClientException: Unable to load partition metadata from com/amazonaws/partitions/endpoints.json
at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:82)
at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
at com.amazonaws.client.builder.AwsClientBuilder.getRegionObject(AwsClientBuilder.java:256)
at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:245)
at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:232)
```

Tried this solution: https://github.com/oracle/graal/issues/1022#issuecomment-468873366 

It didn't help

**Comment by graemerocher** [comment]
Need to add resource config with:

```
{
  "resources" : [ {
    "pattern" : "\\Qcom/amazonaws/partitions/endpoints.json\\E",
    "pattern" : "\\Qcom/amazonaws/sdk/versionInfo.properties\\E"
    }
  ]
}
```

**Comment by ivansynyshynkindgeek** [comment]
Tried this approach with a different versions of resource-config.json file. It resolved an issue with endpoints.json reading but not with versionInfo.properties

I created a public test repo that reproduces an issue: [repo](https://github.com/ivansynyshynkindgeek/files-upload-test)

To build an image it's enough to run ./deploy.sh

AWS lamdba should have valid environment variables AWS_S3_ACCESS_KEY_ID and AWS_S3_SECRET_KEY

Could you please take a look?

**Comment by g3blv** [comment]
@graemerocher is there any update on this issue or is more information needed?

**Comment by pgressa** [comment]
@g3blv @ivansynyshynkindgeek for the micronaut 2.4 we use newer version of aws sdk that has brings graalvm native support directly in the aws sdk module

**Comment by pgressa** [comment]
@g3blv closing this one, re-open when you'll find out the issue persists.
