### ISSUE TITLE
Is micronaut-aws api-gateway-example support graphQL?

### ISSUE THREAD

**Issue by limcheekin** [micronaut-projects/micronaut-aws#93]
Hi there,

I created a GraphQL endpoint based on the following article:
http://lifeinide.com/post/2019-04-15-micronaut-graphql-with-transaction-and-security-support/
It works properly locally.

By referred to the api-gateway-example, I managed to deploy the Micronaut GraphQL API to AWS Lambda and API Gateway. I tested the /ping API, it is working perfectly.

However, when I post a graphql query to /graphql end point, it always return "415 Unsupported Media Type".

I think something is missing, but I not sure what is it, appreciate if you could point me a way on how to make it works.

Thank you.

**Comment by pushpender673** [comment]
I am facing the same issue. I think problem is with content type code written in GraphQLController
As MicronautLambdaHandler checks media type corresponding to string not with the wildcard */* as post request specifies for it.

**Comment by limcheekin** [comment]
Great! Appreciate if you could share more details on how do you solve the issue?

Thanks in advanced.

**Comment by pushpender673** [comment]
I tried with some couple of solutions but due to AWS lambda facing some issues.
Will surely let you know if i got success.

**Comment by limcheekin** [comment]
Great! Thanks.

**Comment by pushpender673** [comment]
You can override the GraphQLController and create your own routing.
Please refer the code snippet.

```
@Controller("/v1")
public class CustomGraphQLController extends GraphQLController {

    private GraphQLJsonSerializer graphQLJsonSerializer;
    private static final Logger LOGGER = LoggerFactory.getLogger(CustomGraphQLController.class);

    public CustomGraphQLController(GraphQLInvocation graphQLInvocation, GraphQLExecutionResultHandler graphQLExecutionResultHandler, GraphQLJsonSerializer graphQLJsonSerializer) {
        super(graphQLInvocation, graphQLExecutionResultHandler, graphQLJsonSerializer);
        this.graphQLJsonSerializer = graphQLJsonSerializer;
    }

    @Post(value = "graphql", produces = MediaType.APPLICATION_JSON, consumes = MediaType.APPLICATION_JSON)
    public Publisher<String> post(@Nullable @QueryValue String query, @Nullable @QueryValue String operationName, @Nullable @QueryValue String variables, @Nullable
    @Body GraphQLRequestBody graphQLRequestBody, HttpRequest httpRequest) {
        LOGGER.info("Handling graphQL Request : {}", graphQLRequestBody);
        return super.post(query, operationName, variables, graphQLJsonSerializer.serialize(graphQLRequestBody), httpRequest);
    }
}
```

Your request URI will look like [www.xyz.com/v1/graphql
](#)

Note : This will only work for application/json content type.

**Comment by limcheekin** [comment]
Great! Thanks for sharing the details of the workaround.

I tried it, it works!
