### ISSUE TITLE
AWS SDK v2 includes out of the box support for GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-aws#930]
See https://github.com/aws/aws-sdk-java-v2/pull/2268

The changes are included in version `2.16.1` so we should [upgrade to use it](https://github.com/micronaut-projects/micronaut-aws/blob/2ec0d5a2dfd341e3cd3b5ef288d4e80241163f55/aws-sdk-v2/build.gradle#L2) and release a new minor version of this module. It would be great if we can do it for Micronaut 2.4.

@sdelamo @pgressa do you think any of you can work on this? If not, I can help :)

**Comment by pgressa** [comment]
@ilopmar sure, I'll look at it, but hard to say whether I'll make it for 2.4.

**Comment by ilopmar** [comment]
No worries, if it doesn't make it for 2.4 it will be for 2.5
